// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

public interface CompactedIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lionweb.CompactedId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 length = 1;</code>
   * @return The length.
   */
  int getLength();

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
