// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

/**
 * Protobuf type {@code lionweb.Containment}
 */
public final class Containment extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:lionweb.Containment)
    ContainmentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Containment.class.getName());
  }
  // Use Containment.newBuilder() to construct.
  private Containment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Containment() {
    children_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Containment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Containment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.lionweb.lioncore.java.serialization.protobuf.Containment.class, io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder.class);
  }

  public static final int METAPOINTER_FIELD_NUMBER = 1;
  private int metaPointer_ = 0;
  /**
   * <code>uint32 metaPointer = 1;</code>
   * @return The metaPointer.
   */
  @java.lang.Override
  public int getMetaPointer() {
    return metaPointer_;
  }

  public static final int CHILDREN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList children_ =
      emptyIntList();
  /**
   * <code>repeated uint32 children = 2;</code>
   * @return A list containing the children.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getChildrenList() {
    return children_;
  }
  /**
   * <code>repeated uint32 children = 2;</code>
   * @return The count of children.
   */
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <code>repeated uint32 children = 2;</code>
   * @param index The index of the element to return.
   * @return The children at the given index.
   */
  public int getChildren(int index) {
    return children_.getInt(index);
  }
  private int childrenMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (metaPointer_ != 0) {
      output.writeUInt32(1, metaPointer_);
    }
    if (getChildrenList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(childrenMemoizedSerializedSize);
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeUInt32NoTag(children_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metaPointer_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, metaPointer_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < children_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(children_.getInt(i));
      }
      size += dataSize;
      if (!getChildrenList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      childrenMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.lionweb.lioncore.java.serialization.protobuf.Containment)) {
      return super.equals(obj);
    }
    io.lionweb.lioncore.java.serialization.protobuf.Containment other = (io.lionweb.lioncore.java.serialization.protobuf.Containment) obj;

    if (getMetaPointer()
        != other.getMetaPointer()) return false;
    if (!getChildrenList()
        .equals(other.getChildrenList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METAPOINTER_FIELD_NUMBER;
    hash = (53 * hash) + getMetaPointer();
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Containment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.lionweb.lioncore.java.serialization.protobuf.Containment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lionweb.Containment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lionweb.Containment)
      io.lionweb.lioncore.java.serialization.protobuf.ContainmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Containment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Containment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.lionweb.lioncore.java.serialization.protobuf.Containment.class, io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder.class);
    }

    // Construct using io.lionweb.lioncore.java.serialization.protobuf.Containment.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metaPointer_ = 0;
      children_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Containment_descriptor;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Containment getDefaultInstanceForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Containment.getDefaultInstance();
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Containment build() {
      io.lionweb.lioncore.java.serialization.protobuf.Containment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Containment buildPartial() {
      io.lionweb.lioncore.java.serialization.protobuf.Containment result = new io.lionweb.lioncore.java.serialization.protobuf.Containment(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.lionweb.lioncore.java.serialization.protobuf.Containment result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metaPointer_ = metaPointer_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        children_.makeImmutable();
        result.children_ = children_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.lionweb.lioncore.java.serialization.protobuf.Containment) {
        return mergeFrom((io.lionweb.lioncore.java.serialization.protobuf.Containment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.lionweb.lioncore.java.serialization.protobuf.Containment other) {
      if (other == io.lionweb.lioncore.java.serialization.protobuf.Containment.getDefaultInstance()) return this;
      if (other.getMetaPointer() != 0) {
        setMetaPointer(other.getMetaPointer());
      }
      if (!other.children_.isEmpty()) {
        if (children_.isEmpty()) {
          children_ = other.children_;
          children_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureChildrenIsMutable();
          children_.addAll(other.children_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              metaPointer_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              int v = input.readUInt32();
              ensureChildrenIsMutable();
              children_.addInt(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureChildrenIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                children_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int metaPointer_ ;
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @return The metaPointer.
     */
    @java.lang.Override
    public int getMetaPointer() {
      return metaPointer_;
    }
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @param value The metaPointer to set.
     * @return This builder for chaining.
     */
    public Builder setMetaPointer(int value) {

      metaPointer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetaPointer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metaPointer_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList children_ = emptyIntList();
    private void ensureChildrenIsMutable() {
      if (!children_.isModifiable()) {
        children_ = makeMutableCopy(children_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated uint32 children = 2;</code>
     * @return A list containing the children.
     */
    public java.util.List<java.lang.Integer>
        getChildrenList() {
      children_.makeImmutable();
      return children_;
    }
    /**
     * <code>repeated uint32 children = 2;</code>
     * @return The count of children.
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated uint32 children = 2;</code>
     * @param index The index of the element to return.
     * @return The children at the given index.
     */
    public int getChildren(int index) {
      return children_.getInt(index);
    }
    /**
     * <code>repeated uint32 children = 2;</code>
     * @param index The index to set the value at.
     * @param value The children to set.
     * @return This builder for chaining.
     */
    public Builder setChildren(
        int index, int value) {

      ensureChildrenIsMutable();
      children_.setInt(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 children = 2;</code>
     * @param value The children to add.
     * @return This builder for chaining.
     */
    public Builder addChildren(int value) {

      ensureChildrenIsMutable();
      children_.addInt(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 children = 2;</code>
     * @param values The children to add.
     * @return This builder for chaining.
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureChildrenIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, children_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 children = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChildren() {
      children_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:lionweb.Containment)
  }

  // @@protoc_insertion_point(class_scope:lionweb.Containment)
  private static final io.lionweb.lioncore.java.serialization.protobuf.Containment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.lionweb.lioncore.java.serialization.protobuf.Containment();
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Containment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Containment>
      PARSER = new com.google.protobuf.AbstractParser<Containment>() {
    @java.lang.Override
    public Containment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Containment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Containment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Containment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

