// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

public interface ContainmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lionweb.Containment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 metaPointer = 1;</code>
   * @return The metaPointer.
   */
  int getMetaPointer();

  /**
   * <code>repeated uint32 children = 2;</code>
   * @return A list containing the children.
   */
  java.util.List<java.lang.Integer> getChildrenList();
  /**
   * <code>repeated uint32 children = 2;</code>
   * @return The count of children.
   */
  int getChildrenCount();
  /**
   * <code>repeated uint32 children = 2;</code>
   * @param index The index of the element to return.
   * @return The children at the given index.
   */
  int getChildren(int index);
}
