// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

public interface MetaPointerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lionweb.MetaPointer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 language = 1;</code>
   * @return The language.
   */
  int getLanguage();

  /**
   * <code>uint32 version = 2;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>uint32 key = 3;</code>
   * @return The key.
   */
  int getKey();
}
