// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

/**
 * Protobuf type {@code lionweb.Node}
 */
public final class Node extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:lionweb.Node)
    NodeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Node.class.getName());
  }
  // Use Node.newBuilder() to construct.
  private Node(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Node() {
    properties_ = java.util.Collections.emptyList();
    containments_ = java.util.Collections.emptyList();
    references_ = java.util.Collections.emptyList();
    annotations_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Node_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Node_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.lionweb.lioncore.java.serialization.protobuf.Node.class, io.lionweb.lioncore.java.serialization.protobuf.Node.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int PARENT_FIELD_NUMBER = 2;
  private int parent_ = 0;
  /**
   * <code>uint32 parent = 2;</code>
   * @return The parent.
   */
  @java.lang.Override
  public int getParent() {
    return parent_;
  }

  public static final int CLASSIFIER_FIELD_NUMBER = 3;
  private int classifier_ = 0;
  /**
   * <code>uint32 classifier = 3;</code>
   * @return The classifier.
   */
  @java.lang.Override
  public int getClassifier() {
    return classifier_;
  }

  public static final int PROPERTIES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Property> properties_;
  /**
   * <code>repeated .lionweb.Property properties = 4;</code>
   */
  @java.lang.Override
  public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Property> getPropertiesList() {
    return properties_;
  }
  /**
   * <code>repeated .lionweb.Property properties = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder> 
      getPropertiesOrBuilderList() {
    return properties_;
  }
  /**
   * <code>repeated .lionweb.Property properties = 4;</code>
   */
  @java.lang.Override
  public int getPropertiesCount() {
    return properties_.size();
  }
  /**
   * <code>repeated .lionweb.Property properties = 4;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Property getProperties(int index) {
    return properties_.get(index);
  }
  /**
   * <code>repeated .lionweb.Property properties = 4;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder getPropertiesOrBuilder(
      int index) {
    return properties_.get(index);
  }

  public static final int CONTAINMENTS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Containment> containments_;
  /**
   * <code>repeated .lionweb.Containment containments = 5;</code>
   */
  @java.lang.Override
  public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Containment> getContainmentsList() {
    return containments_;
  }
  /**
   * <code>repeated .lionweb.Containment containments = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.ContainmentOrBuilder> 
      getContainmentsOrBuilderList() {
    return containments_;
  }
  /**
   * <code>repeated .lionweb.Containment containments = 5;</code>
   */
  @java.lang.Override
  public int getContainmentsCount() {
    return containments_.size();
  }
  /**
   * <code>repeated .lionweb.Containment containments = 5;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Containment getContainments(int index) {
    return containments_.get(index);
  }
  /**
   * <code>repeated .lionweb.Containment containments = 5;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.ContainmentOrBuilder getContainmentsOrBuilder(
      int index) {
    return containments_.get(index);
  }

  public static final int REFERENCES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Reference> references_;
  /**
   * <code>repeated .lionweb.Reference references = 6;</code>
   */
  @java.lang.Override
  public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Reference> getReferencesList() {
    return references_;
  }
  /**
   * <code>repeated .lionweb.Reference references = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.ReferenceOrBuilder> 
      getReferencesOrBuilderList() {
    return references_;
  }
  /**
   * <code>repeated .lionweb.Reference references = 6;</code>
   */
  @java.lang.Override
  public int getReferencesCount() {
    return references_.size();
  }
  /**
   * <code>repeated .lionweb.Reference references = 6;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Reference getReferences(int index) {
    return references_.get(index);
  }
  /**
   * <code>repeated .lionweb.Reference references = 6;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.ReferenceOrBuilder getReferencesOrBuilder(
      int index) {
    return references_.get(index);
  }

  public static final int ANNOTATIONS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList annotations_ =
      emptyIntList();
  /**
   * <code>repeated uint32 annotations = 7;</code>
   * @return A list containing the annotations.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getAnnotationsList() {
    return annotations_;
  }
  /**
   * <code>repeated uint32 annotations = 7;</code>
   * @return The count of annotations.
   */
  public int getAnnotationsCount() {
    return annotations_.size();
  }
  /**
   * <code>repeated uint32 annotations = 7;</code>
   * @param index The index of the element to return.
   * @return The annotations at the given index.
   */
  public int getAnnotations(int index) {
    return annotations_.getInt(index);
  }
  private int annotationsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (parent_ != 0) {
      output.writeUInt32(2, parent_);
    }
    if (classifier_ != 0) {
      output.writeUInt32(3, classifier_);
    }
    for (int i = 0; i < properties_.size(); i++) {
      output.writeMessage(4, properties_.get(i));
    }
    for (int i = 0; i < containments_.size(); i++) {
      output.writeMessage(5, containments_.get(i));
    }
    for (int i = 0; i < references_.size(); i++) {
      output.writeMessage(6, references_.get(i));
    }
    if (getAnnotationsList().size() > 0) {
      output.writeUInt32NoTag(58);
      output.writeUInt32NoTag(annotationsMemoizedSerializedSize);
    }
    for (int i = 0; i < annotations_.size(); i++) {
      output.writeUInt32NoTag(annotations_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (parent_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, parent_);
    }
    if (classifier_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, classifier_);
    }
    for (int i = 0; i < properties_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, properties_.get(i));
    }
    for (int i = 0; i < containments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, containments_.get(i));
    }
    for (int i = 0; i < references_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, references_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < annotations_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(annotations_.getInt(i));
      }
      size += dataSize;
      if (!getAnnotationsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      annotationsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.lionweb.lioncore.java.serialization.protobuf.Node)) {
      return super.equals(obj);
    }
    io.lionweb.lioncore.java.serialization.protobuf.Node other = (io.lionweb.lioncore.java.serialization.protobuf.Node) obj;

    if (getId()
        != other.getId()) return false;
    if (getParent()
        != other.getParent()) return false;
    if (getClassifier()
        != other.getClassifier()) return false;
    if (!getPropertiesList()
        .equals(other.getPropertiesList())) return false;
    if (!getContainmentsList()
        .equals(other.getContainmentsList())) return false;
    if (!getReferencesList()
        .equals(other.getReferencesList())) return false;
    if (!getAnnotationsList()
        .equals(other.getAnnotationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + PARENT_FIELD_NUMBER;
    hash = (53 * hash) + getParent();
    hash = (37 * hash) + CLASSIFIER_FIELD_NUMBER;
    hash = (53 * hash) + getClassifier();
    if (getPropertiesCount() > 0) {
      hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + getPropertiesList().hashCode();
    }
    if (getContainmentsCount() > 0) {
      hash = (37 * hash) + CONTAINMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContainmentsList().hashCode();
    }
    if (getReferencesCount() > 0) {
      hash = (37 * hash) + REFERENCES_FIELD_NUMBER;
      hash = (53 * hash) + getReferencesList().hashCode();
    }
    if (getAnnotationsCount() > 0) {
      hash = (37 * hash) + ANNOTATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getAnnotationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Node parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.lionweb.lioncore.java.serialization.protobuf.Node prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lionweb.Node}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lionweb.Node)
      io.lionweb.lioncore.java.serialization.protobuf.NodeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.lionweb.lioncore.java.serialization.protobuf.Node.class, io.lionweb.lioncore.java.serialization.protobuf.Node.Builder.class);
    }

    // Construct using io.lionweb.lioncore.java.serialization.protobuf.Node.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      parent_ = 0;
      classifier_ = 0;
      if (propertiesBuilder_ == null) {
        properties_ = java.util.Collections.emptyList();
      } else {
        properties_ = null;
        propertiesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (containmentsBuilder_ == null) {
        containments_ = java.util.Collections.emptyList();
      } else {
        containments_ = null;
        containmentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (referencesBuilder_ == null) {
        references_ = java.util.Collections.emptyList();
      } else {
        references_ = null;
        referencesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      annotations_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Node_descriptor;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Node getDefaultInstanceForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Node.getDefaultInstance();
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Node build() {
      io.lionweb.lioncore.java.serialization.protobuf.Node result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Node buildPartial() {
      io.lionweb.lioncore.java.serialization.protobuf.Node result = new io.lionweb.lioncore.java.serialization.protobuf.Node(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.lionweb.lioncore.java.serialization.protobuf.Node result) {
      if (propertiesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          properties_ = java.util.Collections.unmodifiableList(properties_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.properties_ = properties_;
      } else {
        result.properties_ = propertiesBuilder_.build();
      }
      if (containmentsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          containments_ = java.util.Collections.unmodifiableList(containments_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.containments_ = containments_;
      } else {
        result.containments_ = containmentsBuilder_.build();
      }
      if (referencesBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          references_ = java.util.Collections.unmodifiableList(references_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.references_ = references_;
      } else {
        result.references_ = referencesBuilder_.build();
      }
    }

    private void buildPartial0(io.lionweb.lioncore.java.serialization.protobuf.Node result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.parent_ = parent_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.classifier_ = classifier_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        annotations_.makeImmutable();
        result.annotations_ = annotations_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.lionweb.lioncore.java.serialization.protobuf.Node) {
        return mergeFrom((io.lionweb.lioncore.java.serialization.protobuf.Node)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.lionweb.lioncore.java.serialization.protobuf.Node other) {
      if (other == io.lionweb.lioncore.java.serialization.protobuf.Node.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getParent() != 0) {
        setParent(other.getParent());
      }
      if (other.getClassifier() != 0) {
        setClassifier(other.getClassifier());
      }
      if (propertiesBuilder_ == null) {
        if (!other.properties_.isEmpty()) {
          if (properties_.isEmpty()) {
            properties_ = other.properties_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePropertiesIsMutable();
            properties_.addAll(other.properties_);
          }
          onChanged();
        }
      } else {
        if (!other.properties_.isEmpty()) {
          if (propertiesBuilder_.isEmpty()) {
            propertiesBuilder_.dispose();
            propertiesBuilder_ = null;
            properties_ = other.properties_;
            bitField0_ = (bitField0_ & ~0x00000008);
            propertiesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPropertiesFieldBuilder() : null;
          } else {
            propertiesBuilder_.addAllMessages(other.properties_);
          }
        }
      }
      if (containmentsBuilder_ == null) {
        if (!other.containments_.isEmpty()) {
          if (containments_.isEmpty()) {
            containments_ = other.containments_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureContainmentsIsMutable();
            containments_.addAll(other.containments_);
          }
          onChanged();
        }
      } else {
        if (!other.containments_.isEmpty()) {
          if (containmentsBuilder_.isEmpty()) {
            containmentsBuilder_.dispose();
            containmentsBuilder_ = null;
            containments_ = other.containments_;
            bitField0_ = (bitField0_ & ~0x00000010);
            containmentsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getContainmentsFieldBuilder() : null;
          } else {
            containmentsBuilder_.addAllMessages(other.containments_);
          }
        }
      }
      if (referencesBuilder_ == null) {
        if (!other.references_.isEmpty()) {
          if (references_.isEmpty()) {
            references_ = other.references_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureReferencesIsMutable();
            references_.addAll(other.references_);
          }
          onChanged();
        }
      } else {
        if (!other.references_.isEmpty()) {
          if (referencesBuilder_.isEmpty()) {
            referencesBuilder_.dispose();
            referencesBuilder_ = null;
            references_ = other.references_;
            bitField0_ = (bitField0_ & ~0x00000020);
            referencesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getReferencesFieldBuilder() : null;
          } else {
            referencesBuilder_.addAllMessages(other.references_);
          }
        }
      }
      if (!other.annotations_.isEmpty()) {
        if (annotations_.isEmpty()) {
          annotations_ = other.annotations_;
          annotations_.makeImmutable();
          bitField0_ |= 0x00000040;
        } else {
          ensureAnnotationsIsMutable();
          annotations_.addAll(other.annotations_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              parent_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              classifier_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              io.lionweb.lioncore.java.serialization.protobuf.Property m =
                  input.readMessage(
                      io.lionweb.lioncore.java.serialization.protobuf.Property.parser(),
                      extensionRegistry);
              if (propertiesBuilder_ == null) {
                ensurePropertiesIsMutable();
                properties_.add(m);
              } else {
                propertiesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              io.lionweb.lioncore.java.serialization.protobuf.Containment m =
                  input.readMessage(
                      io.lionweb.lioncore.java.serialization.protobuf.Containment.parser(),
                      extensionRegistry);
              if (containmentsBuilder_ == null) {
                ensureContainmentsIsMutable();
                containments_.add(m);
              } else {
                containmentsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              io.lionweb.lioncore.java.serialization.protobuf.Reference m =
                  input.readMessage(
                      io.lionweb.lioncore.java.serialization.protobuf.Reference.parser(),
                      extensionRegistry);
              if (referencesBuilder_ == null) {
                ensureReferencesIsMutable();
                references_.add(m);
              } else {
                referencesBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 56: {
              int v = input.readUInt32();
              ensureAnnotationsIsMutable();
              annotations_.addInt(v);
              break;
            } // case 56
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureAnnotationsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                annotations_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private int parent_ ;
    /**
     * <code>uint32 parent = 2;</code>
     * @return The parent.
     */
    @java.lang.Override
    public int getParent() {
      return parent_;
    }
    /**
     * <code>uint32 parent = 2;</code>
     * @param value The parent to set.
     * @return This builder for chaining.
     */
    public Builder setParent(int value) {

      parent_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 parent = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      parent_ = 0;
      onChanged();
      return this;
    }

    private int classifier_ ;
    /**
     * <code>uint32 classifier = 3;</code>
     * @return The classifier.
     */
    @java.lang.Override
    public int getClassifier() {
      return classifier_;
    }
    /**
     * <code>uint32 classifier = 3;</code>
     * @param value The classifier to set.
     * @return This builder for chaining.
     */
    public Builder setClassifier(int value) {

      classifier_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 classifier = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassifier() {
      bitField0_ = (bitField0_ & ~0x00000004);
      classifier_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Property> properties_ =
      java.util.Collections.emptyList();
    private void ensurePropertiesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        properties_ = new java.util.ArrayList<io.lionweb.lioncore.java.serialization.protobuf.Property>(properties_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.Property, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder, io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder> propertiesBuilder_;

    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Property> getPropertiesList() {
      if (propertiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(properties_);
      } else {
        return propertiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public int getPropertiesCount() {
      if (propertiesBuilder_ == null) {
        return properties_.size();
      } else {
        return propertiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Property getProperties(int index) {
      if (propertiesBuilder_ == null) {
        return properties_.get(index);
      } else {
        return propertiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder setProperties(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Property value) {
      if (propertiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertiesIsMutable();
        properties_.set(index, value);
        onChanged();
      } else {
        propertiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder setProperties(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder builderForValue) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        properties_.set(index, builderForValue.build());
        onChanged();
      } else {
        propertiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder addProperties(io.lionweb.lioncore.java.serialization.protobuf.Property value) {
      if (propertiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertiesIsMutable();
        properties_.add(value);
        onChanged();
      } else {
        propertiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder addProperties(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Property value) {
      if (propertiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropertiesIsMutable();
        properties_.add(index, value);
        onChanged();
      } else {
        propertiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder addProperties(
        io.lionweb.lioncore.java.serialization.protobuf.Property.Builder builderForValue) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        properties_.add(builderForValue.build());
        onChanged();
      } else {
        propertiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder addProperties(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder builderForValue) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        properties_.add(index, builderForValue.build());
        onChanged();
      } else {
        propertiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder addAllProperties(
        java.lang.Iterable<? extends io.lionweb.lioncore.java.serialization.protobuf.Property> values) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, properties_);
        onChanged();
      } else {
        propertiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder clearProperties() {
      if (propertiesBuilder_ == null) {
        properties_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        propertiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public Builder removeProperties(int index) {
      if (propertiesBuilder_ == null) {
        ensurePropertiesIsMutable();
        properties_.remove(index);
        onChanged();
      } else {
        propertiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Property.Builder getPropertiesBuilder(
        int index) {
      return getPropertiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder getPropertiesOrBuilder(
        int index) {
      if (propertiesBuilder_ == null) {
        return properties_.get(index);  } else {
        return propertiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder> 
         getPropertiesOrBuilderList() {
      if (propertiesBuilder_ != null) {
        return propertiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(properties_);
      }
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Property.Builder addPropertiesBuilder() {
      return getPropertiesFieldBuilder().addBuilder(
          io.lionweb.lioncore.java.serialization.protobuf.Property.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Property.Builder addPropertiesBuilder(
        int index) {
      return getPropertiesFieldBuilder().addBuilder(
          index, io.lionweb.lioncore.java.serialization.protobuf.Property.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.Property properties = 4;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Property.Builder> 
         getPropertiesBuilderList() {
      return getPropertiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.Property, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder, io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder> 
        getPropertiesFieldBuilder() {
      if (propertiesBuilder_ == null) {
        propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.lionweb.lioncore.java.serialization.protobuf.Property, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder, io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder>(
                properties_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        properties_ = null;
      }
      return propertiesBuilder_;
    }

    private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Containment> containments_ =
      java.util.Collections.emptyList();
    private void ensureContainmentsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        containments_ = new java.util.ArrayList<io.lionweb.lioncore.java.serialization.protobuf.Containment>(containments_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.Containment, io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder, io.lionweb.lioncore.java.serialization.protobuf.ContainmentOrBuilder> containmentsBuilder_;

    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Containment> getContainmentsList() {
      if (containmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(containments_);
      } else {
        return containmentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public int getContainmentsCount() {
      if (containmentsBuilder_ == null) {
        return containments_.size();
      } else {
        return containmentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Containment getContainments(int index) {
      if (containmentsBuilder_ == null) {
        return containments_.get(index);
      } else {
        return containmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder setContainments(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Containment value) {
      if (containmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContainmentsIsMutable();
        containments_.set(index, value);
        onChanged();
      } else {
        containmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder setContainments(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder builderForValue) {
      if (containmentsBuilder_ == null) {
        ensureContainmentsIsMutable();
        containments_.set(index, builderForValue.build());
        onChanged();
      } else {
        containmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder addContainments(io.lionweb.lioncore.java.serialization.protobuf.Containment value) {
      if (containmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContainmentsIsMutable();
        containments_.add(value);
        onChanged();
      } else {
        containmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder addContainments(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Containment value) {
      if (containmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContainmentsIsMutable();
        containments_.add(index, value);
        onChanged();
      } else {
        containmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder addContainments(
        io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder builderForValue) {
      if (containmentsBuilder_ == null) {
        ensureContainmentsIsMutable();
        containments_.add(builderForValue.build());
        onChanged();
      } else {
        containmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder addContainments(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder builderForValue) {
      if (containmentsBuilder_ == null) {
        ensureContainmentsIsMutable();
        containments_.add(index, builderForValue.build());
        onChanged();
      } else {
        containmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder addAllContainments(
        java.lang.Iterable<? extends io.lionweb.lioncore.java.serialization.protobuf.Containment> values) {
      if (containmentsBuilder_ == null) {
        ensureContainmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, containments_);
        onChanged();
      } else {
        containmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder clearContainments() {
      if (containmentsBuilder_ == null) {
        containments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        containmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public Builder removeContainments(int index) {
      if (containmentsBuilder_ == null) {
        ensureContainmentsIsMutable();
        containments_.remove(index);
        onChanged();
      } else {
        containmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder getContainmentsBuilder(
        int index) {
      return getContainmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.ContainmentOrBuilder getContainmentsOrBuilder(
        int index) {
      if (containmentsBuilder_ == null) {
        return containments_.get(index);  } else {
        return containmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.ContainmentOrBuilder> 
         getContainmentsOrBuilderList() {
      if (containmentsBuilder_ != null) {
        return containmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(containments_);
      }
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder addContainmentsBuilder() {
      return getContainmentsFieldBuilder().addBuilder(
          io.lionweb.lioncore.java.serialization.protobuf.Containment.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder addContainmentsBuilder(
        int index) {
      return getContainmentsFieldBuilder().addBuilder(
          index, io.lionweb.lioncore.java.serialization.protobuf.Containment.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.Containment containments = 5;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder> 
         getContainmentsBuilderList() {
      return getContainmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.Containment, io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder, io.lionweb.lioncore.java.serialization.protobuf.ContainmentOrBuilder> 
        getContainmentsFieldBuilder() {
      if (containmentsBuilder_ == null) {
        containmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.lionweb.lioncore.java.serialization.protobuf.Containment, io.lionweb.lioncore.java.serialization.protobuf.Containment.Builder, io.lionweb.lioncore.java.serialization.protobuf.ContainmentOrBuilder>(
                containments_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        containments_ = null;
      }
      return containmentsBuilder_;
    }

    private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Reference> references_ =
      java.util.Collections.emptyList();
    private void ensureReferencesIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        references_ = new java.util.ArrayList<io.lionweb.lioncore.java.serialization.protobuf.Reference>(references_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.Reference, io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder, io.lionweb.lioncore.java.serialization.protobuf.ReferenceOrBuilder> referencesBuilder_;

    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Reference> getReferencesList() {
      if (referencesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(references_);
      } else {
        return referencesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public int getReferencesCount() {
      if (referencesBuilder_ == null) {
        return references_.size();
      } else {
        return referencesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Reference getReferences(int index) {
      if (referencesBuilder_ == null) {
        return references_.get(index);
      } else {
        return referencesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder setReferences(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Reference value) {
      if (referencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReferencesIsMutable();
        references_.set(index, value);
        onChanged();
      } else {
        referencesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder setReferences(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder builderForValue) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        references_.set(index, builderForValue.build());
        onChanged();
      } else {
        referencesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder addReferences(io.lionweb.lioncore.java.serialization.protobuf.Reference value) {
      if (referencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReferencesIsMutable();
        references_.add(value);
        onChanged();
      } else {
        referencesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder addReferences(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Reference value) {
      if (referencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReferencesIsMutable();
        references_.add(index, value);
        onChanged();
      } else {
        referencesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder addReferences(
        io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder builderForValue) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        references_.add(builderForValue.build());
        onChanged();
      } else {
        referencesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder addReferences(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder builderForValue) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        references_.add(index, builderForValue.build());
        onChanged();
      } else {
        referencesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder addAllReferences(
        java.lang.Iterable<? extends io.lionweb.lioncore.java.serialization.protobuf.Reference> values) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, references_);
        onChanged();
      } else {
        referencesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder clearReferences() {
      if (referencesBuilder_ == null) {
        references_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        referencesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public Builder removeReferences(int index) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        references_.remove(index);
        onChanged();
      } else {
        referencesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder getReferencesBuilder(
        int index) {
      return getReferencesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceOrBuilder getReferencesOrBuilder(
        int index) {
      if (referencesBuilder_ == null) {
        return references_.get(index);  } else {
        return referencesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.ReferenceOrBuilder> 
         getReferencesOrBuilderList() {
      if (referencesBuilder_ != null) {
        return referencesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(references_);
      }
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder addReferencesBuilder() {
      return getReferencesFieldBuilder().addBuilder(
          io.lionweb.lioncore.java.serialization.protobuf.Reference.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder addReferencesBuilder(
        int index) {
      return getReferencesFieldBuilder().addBuilder(
          index, io.lionweb.lioncore.java.serialization.protobuf.Reference.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.Reference references = 6;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder> 
         getReferencesBuilderList() {
      return getReferencesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.Reference, io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder, io.lionweb.lioncore.java.serialization.protobuf.ReferenceOrBuilder> 
        getReferencesFieldBuilder() {
      if (referencesBuilder_ == null) {
        referencesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.lionweb.lioncore.java.serialization.protobuf.Reference, io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder, io.lionweb.lioncore.java.serialization.protobuf.ReferenceOrBuilder>(
                references_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        references_ = null;
      }
      return referencesBuilder_;
    }

    private com.google.protobuf.Internal.IntList annotations_ = emptyIntList();
    private void ensureAnnotationsIsMutable() {
      if (!annotations_.isModifiable()) {
        annotations_ = makeMutableCopy(annotations_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>repeated uint32 annotations = 7;</code>
     * @return A list containing the annotations.
     */
    public java.util.List<java.lang.Integer>
        getAnnotationsList() {
      annotations_.makeImmutable();
      return annotations_;
    }
    /**
     * <code>repeated uint32 annotations = 7;</code>
     * @return The count of annotations.
     */
    public int getAnnotationsCount() {
      return annotations_.size();
    }
    /**
     * <code>repeated uint32 annotations = 7;</code>
     * @param index The index of the element to return.
     * @return The annotations at the given index.
     */
    public int getAnnotations(int index) {
      return annotations_.getInt(index);
    }
    /**
     * <code>repeated uint32 annotations = 7;</code>
     * @param index The index to set the value at.
     * @param value The annotations to set.
     * @return This builder for chaining.
     */
    public Builder setAnnotations(
        int index, int value) {

      ensureAnnotationsIsMutable();
      annotations_.setInt(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 annotations = 7;</code>
     * @param value The annotations to add.
     * @return This builder for chaining.
     */
    public Builder addAnnotations(int value) {

      ensureAnnotationsIsMutable();
      annotations_.addInt(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 annotations = 7;</code>
     * @param values The annotations to add.
     * @return This builder for chaining.
     */
    public Builder addAllAnnotations(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureAnnotationsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, annotations_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 annotations = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnnotations() {
      annotations_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:lionweb.Node)
  }

  // @@protoc_insertion_point(class_scope:lionweb.Node)
  private static final io.lionweb.lioncore.java.serialization.protobuf.Node DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.lionweb.lioncore.java.serialization.protobuf.Node();
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Node getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Node>
      PARSER = new com.google.protobuf.AbstractParser<Node>() {
    @java.lang.Override
    public Node parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Node> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Node> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Node getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

