// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

public interface PropertyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lionweb.Property)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 metaPointer = 1;</code>
   * @return The metaPointer.
   */
  int getMetaPointer();

  /**
   * <code>bool boolean = 2;</code>
   * @return Whether the boolean field is set.
   */
  boolean hasBoolean();
  /**
   * <code>bool boolean = 2;</code>
   * @return The boolean.
   */
  boolean getBoolean();

  /**
   * <code>int32 integer = 3;</code>
   * @return Whether the integer field is set.
   */
  boolean hasInteger();
  /**
   * <code>int32 integer = 3;</code>
   * @return The integer.
   */
  int getInteger();

  /**
   * <code>uint32 string = 4;</code>
   * @return Whether the string field is set.
   */
  boolean hasString();
  /**
   * <code>uint32 string = 4;</code>
   * @return The string.
   */
  int getString();

  io.lionweb.lioncore.java.serialization.protobuf.Property.ValueCase getValueCase();
}
