// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

public interface PropertyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lionweb.Property)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 metaPointer = 1;</code>
   * @return The metaPointer.
   */
  int getMetaPointer();

  /**
   * <code>uint32 value = 2;</code>
   * @return The value.
   */
  int getValue();
}
