// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

/**
 * Protobuf type {@code lionweb.Property}
 */
public final class Property extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:lionweb.Property)
    PropertyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Property.class.getName());
  }
  // Use Property.newBuilder() to construct.
  private Property(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Property() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.lionweb.lioncore.java.serialization.protobuf.Property.class, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder.class);
  }

  private int valueCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    BOOLEAN(2),
    INTEGER(3),
    STRING(4),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 2: return BOOLEAN;
        case 3: return INTEGER;
        case 4: return STRING;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int METAPOINTER_FIELD_NUMBER = 1;
  private int metaPointer_ = 0;
  /**
   * <code>uint32 metaPointer = 1;</code>
   * @return The metaPointer.
   */
  @java.lang.Override
  public int getMetaPointer() {
    return metaPointer_;
  }

  public static final int BOOLEAN_FIELD_NUMBER = 2;
  /**
   * <code>bool boolean = 2;</code>
   * @return Whether the boolean field is set.
   */
  @java.lang.Override
  public boolean hasBoolean() {
    return valueCase_ == 2;
  }
  /**
   * <code>bool boolean = 2;</code>
   * @return The boolean.
   */
  @java.lang.Override
  public boolean getBoolean() {
    if (valueCase_ == 2) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }

  public static final int INTEGER_FIELD_NUMBER = 3;
  /**
   * <code>int32 integer = 3;</code>
   * @return Whether the integer field is set.
   */
  @java.lang.Override
  public boolean hasInteger() {
    return valueCase_ == 3;
  }
  /**
   * <code>int32 integer = 3;</code>
   * @return The integer.
   */
  @java.lang.Override
  public int getInteger() {
    if (valueCase_ == 3) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }

  public static final int STRING_FIELD_NUMBER = 4;
  /**
   * <code>uint32 string = 4;</code>
   * @return Whether the string field is set.
   */
  @java.lang.Override
  public boolean hasString() {
    return valueCase_ == 4;
  }
  /**
   * <code>uint32 string = 4;</code>
   * @return The string.
   */
  @java.lang.Override
  public int getString() {
    if (valueCase_ == 4) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metaPointer_ != 0) {
      output.writeUInt32(1, metaPointer_);
    }
    if (valueCase_ == 2) {
      output.writeBool(
          2, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 3) {
      output.writeInt32(
          3, (int)((java.lang.Integer) value_));
    }
    if (valueCase_ == 4) {
      output.writeUInt32(
          4, (int)((java.lang.Integer) value_));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metaPointer_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, metaPointer_);
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            2, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            3, (int)((java.lang.Integer) value_));
    }
    if (valueCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(
            4, (int)((java.lang.Integer) value_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.lionweb.lioncore.java.serialization.protobuf.Property)) {
      return super.equals(obj);
    }
    io.lionweb.lioncore.java.serialization.protobuf.Property other = (io.lionweb.lioncore.java.serialization.protobuf.Property) obj;

    if (getMetaPointer()
        != other.getMetaPointer()) return false;
    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 2:
        if (getBoolean()
            != other.getBoolean()) return false;
        break;
      case 3:
        if (getInteger()
            != other.getInteger()) return false;
        break;
      case 4:
        if (getString()
            != other.getString()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METAPOINTER_FIELD_NUMBER;
    hash = (53 * hash) + getMetaPointer();
    switch (valueCase_) {
      case 2:
        hash = (37 * hash) + BOOLEAN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolean());
        break;
      case 3:
        hash = (37 * hash) + INTEGER_FIELD_NUMBER;
        hash = (53 * hash) + getInteger();
        break;
      case 4:
        hash = (37 * hash) + STRING_FIELD_NUMBER;
        hash = (53 * hash) + getString();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.lionweb.lioncore.java.serialization.protobuf.Property prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lionweb.Property}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lionweb.Property)
      io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.lionweb.lioncore.java.serialization.protobuf.Property.class, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder.class);
    }

    // Construct using io.lionweb.lioncore.java.serialization.protobuf.Property.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metaPointer_ = 0;
      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_descriptor;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Property getDefaultInstanceForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Property.getDefaultInstance();
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Property build() {
      io.lionweb.lioncore.java.serialization.protobuf.Property result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Property buildPartial() {
      io.lionweb.lioncore.java.serialization.protobuf.Property result = new io.lionweb.lioncore.java.serialization.protobuf.Property(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.lionweb.lioncore.java.serialization.protobuf.Property result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metaPointer_ = metaPointer_;
      }
    }

    private void buildPartialOneofs(io.lionweb.lioncore.java.serialization.protobuf.Property result) {
      result.valueCase_ = valueCase_;
      result.value_ = this.value_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.lionweb.lioncore.java.serialization.protobuf.Property) {
        return mergeFrom((io.lionweb.lioncore.java.serialization.protobuf.Property)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.lionweb.lioncore.java.serialization.protobuf.Property other) {
      if (other == io.lionweb.lioncore.java.serialization.protobuf.Property.getDefaultInstance()) return this;
      if (other.getMetaPointer() != 0) {
        setMetaPointer(other.getMetaPointer());
      }
      switch (other.getValueCase()) {
        case BOOLEAN: {
          setBoolean(other.getBoolean());
          break;
        }
        case INTEGER: {
          setInteger(other.getInteger());
          break;
        }
        case STRING: {
          setString(other.getString());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              metaPointer_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              value_ = input.readBool();
              valueCase_ = 2;
              break;
            } // case 16
            case 24: {
              value_ = input.readInt32();
              valueCase_ = 3;
              break;
            } // case 24
            case 32: {
              value_ = input.readUInt32();
              valueCase_ = 4;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int metaPointer_ ;
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @return The metaPointer.
     */
    @java.lang.Override
    public int getMetaPointer() {
      return metaPointer_;
    }
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @param value The metaPointer to set.
     * @return This builder for chaining.
     */
    public Builder setMetaPointer(int value) {

      metaPointer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetaPointer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metaPointer_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>bool boolean = 2;</code>
     * @return Whether the boolean field is set.
     */
    public boolean hasBoolean() {
      return valueCase_ == 2;
    }
    /**
     * <code>bool boolean = 2;</code>
     * @return The boolean.
     */
    public boolean getBoolean() {
      if (valueCase_ == 2) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }
    /**
     * <code>bool boolean = 2;</code>
     * @param value The boolean to set.
     * @return This builder for chaining.
     */
    public Builder setBoolean(boolean value) {

      valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool boolean = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolean() {
      if (valueCase_ == 2) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int32 integer = 3;</code>
     * @return Whether the integer field is set.
     */
    public boolean hasInteger() {
      return valueCase_ == 3;
    }
    /**
     * <code>int32 integer = 3;</code>
     * @return The integer.
     */
    public int getInteger() {
      if (valueCase_ == 3) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }
    /**
     * <code>int32 integer = 3;</code>
     * @param value The integer to set.
     * @return This builder for chaining.
     */
    public Builder setInteger(int value) {

      valueCase_ = 3;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 integer = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInteger() {
      if (valueCase_ == 3) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>uint32 string = 4;</code>
     * @return Whether the string field is set.
     */
    public boolean hasString() {
      return valueCase_ == 4;
    }
    /**
     * <code>uint32 string = 4;</code>
     * @return The string.
     */
    public int getString() {
      if (valueCase_ == 4) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }
    /**
     * <code>uint32 string = 4;</code>
     * @param value The string to set.
     * @return This builder for chaining.
     */
    public Builder setString(int value) {

      valueCase_ = 4;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 string = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearString() {
      if (valueCase_ == 4) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    // @@protoc_insertion_point(builder_scope:lionweb.Property)
  }

  // @@protoc_insertion_point(class_scope:lionweb.Property)
  private static final io.lionweb.lioncore.java.serialization.protobuf.Property DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.lionweb.lioncore.java.serialization.protobuf.Property();
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Property getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Property>
      PARSER = new com.google.protobuf.AbstractParser<Property>() {
    @java.lang.Override
    public Property parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Property> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Property> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Property getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

