// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

/**
 * Protobuf type {@code lionweb.Property}
 */
public final class Property extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:lionweb.Property)
    PropertyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Property.class.getName());
  }
  // Use Property.newBuilder() to construct.
  private Property(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Property() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.lionweb.lioncore.java.serialization.protobuf.Property.class, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder.class);
  }

  public static final int METAPOINTER_FIELD_NUMBER = 1;
  private int metaPointer_ = 0;
  /**
   * <code>uint32 metaPointer = 1;</code>
   * @return The metaPointer.
   */
  @java.lang.Override
  public int getMetaPointer() {
    return metaPointer_;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private int value_ = 0;
  /**
   * <code>uint32 value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public int getValue() {
    return value_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metaPointer_ != 0) {
      output.writeUInt32(1, metaPointer_);
    }
    if (value_ != 0) {
      output.writeUInt32(2, value_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metaPointer_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, metaPointer_);
    }
    if (value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, value_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.lionweb.lioncore.java.serialization.protobuf.Property)) {
      return super.equals(obj);
    }
    io.lionweb.lioncore.java.serialization.protobuf.Property other = (io.lionweb.lioncore.java.serialization.protobuf.Property) obj;

    if (getMetaPointer()
        != other.getMetaPointer()) return false;
    if (getValue()
        != other.getValue()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METAPOINTER_FIELD_NUMBER;
    hash = (53 * hash) + getMetaPointer();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Property parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.lionweb.lioncore.java.serialization.protobuf.Property prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lionweb.Property}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lionweb.Property)
      io.lionweb.lioncore.java.serialization.protobuf.PropertyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.lionweb.lioncore.java.serialization.protobuf.Property.class, io.lionweb.lioncore.java.serialization.protobuf.Property.Builder.class);
    }

    // Construct using io.lionweb.lioncore.java.serialization.protobuf.Property.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metaPointer_ = 0;
      value_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Property_descriptor;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Property getDefaultInstanceForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Property.getDefaultInstance();
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Property build() {
      io.lionweb.lioncore.java.serialization.protobuf.Property result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Property buildPartial() {
      io.lionweb.lioncore.java.serialization.protobuf.Property result = new io.lionweb.lioncore.java.serialization.protobuf.Property(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.lionweb.lioncore.java.serialization.protobuf.Property result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metaPointer_ = metaPointer_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = value_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.lionweb.lioncore.java.serialization.protobuf.Property) {
        return mergeFrom((io.lionweb.lioncore.java.serialization.protobuf.Property)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.lionweb.lioncore.java.serialization.protobuf.Property other) {
      if (other == io.lionweb.lioncore.java.serialization.protobuf.Property.getDefaultInstance()) return this;
      if (other.getMetaPointer() != 0) {
        setMetaPointer(other.getMetaPointer());
      }
      if (other.getValue() != 0) {
        setValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              metaPointer_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              value_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int metaPointer_ ;
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @return The metaPointer.
     */
    @java.lang.Override
    public int getMetaPointer() {
      return metaPointer_;
    }
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @param value The metaPointer to set.
     * @return This builder for chaining.
     */
    public Builder setMetaPointer(int value) {

      metaPointer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetaPointer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metaPointer_ = 0;
      onChanged();
      return this;
    }

    private int value_ ;
    /**
     * <code>uint32 value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public int getValue() {
      return value_;
    }
    /**
     * <code>uint32 value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(int value) {

      value_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:lionweb.Property)
  }

  // @@protoc_insertion_point(class_scope:lionweb.Property)
  private static final io.lionweb.lioncore.java.serialization.protobuf.Property DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.lionweb.lioncore.java.serialization.protobuf.Property();
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Property getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Property>
      PARSER = new com.google.protobuf.AbstractParser<Property>() {
    @java.lang.Override
    public Property parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Property> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Property> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Property getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

