// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto
// Protobuf Java Version: 4.26.1

package io.lionweb.lioncore.java.serialization.protobuf;

public final class Protobuf {
  private Protobuf() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Protobuf.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_SerializationChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_SerializationChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_SerializationChunk_IdStringsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_SerializationChunk_IdStringsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_SerializationChunk_MetaPointersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_SerializationChunk_MetaPointersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_SerializationChunk_StringsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_SerializationChunk_StringsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_CompactedId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_CompactedId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_MetaPointer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_MetaPointer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_UsedLanguage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_UsedLanguage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_Property_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_Property_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_Containment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_Containment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_Reference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_Reference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lionweb_ReferenceTarget_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lionweb_ReferenceTarget_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlionweb.proto\022\007lionweb\"\202\004\n\022Serializati" +
      "onChunk\022\"\n\032serializationFormatVersion\030\001 " +
      "\001(\t\022=\n\tidStrings\030\002 \003(\0132*.lionweb.Seriali" +
      "zationChunk.IdStringsEntry\022C\n\014metaPointe" +
      "rs\030\003 \003(\0132-.lionweb.SerializationChunk.Me" +
      "taPointersEntry\0229\n\007strings\030\004 \003(\0132(.lionw" +
      "eb.SerializationChunk.StringsEntry\022(\n\tla" +
      "nguages\030\005 \003(\0132\025.lionweb.UsedLanguage\022\034\n\005" +
      "nodes\030\006 \003(\0132\r.lionweb.Node\032F\n\016IdStringsE" +
      "ntry\022\013\n\003key\030\001 \001(\r\022#\n\005value\030\002 \001(\0132\024.lionw" +
      "eb.CompactedId:\0028\001\032I\n\021MetaPointersEntry\022" +
      "\013\n\003key\030\001 \001(\r\022#\n\005value\030\002 \001(\0132\024.lionweb.Me" +
      "taPointer:\0028\001\032.\n\014StringsEntry\022\013\n\003key\030\001 \001" +
      "(\r\022\r\n\005value\030\002 \001(\t:\0028\001\",\n\013CompactedId\022\016\n\006" +
      "length\030\001 \001(\r\022\r\n\005value\030\002 \001(\014\"=\n\013MetaPoint" +
      "er\022\020\n\010language\030\001 \001(\r\022\017\n\007version\030\002 \001(\r\022\013\n" +
      "\003key\030\003 \001(\r\"1\n\014UsedLanguage\022\020\n\010language\030\001" +
      " \001(\r\022\017\n\007version\030\002 \001(\r\"\306\001\n\004Node\022\n\n\002id\030\001 \001" +
      "(\r\022\016\n\006parent\030\002 \001(\r\022\022\n\nclassifier\030\003 \001(\r\022%" +
      "\n\nproperties\030\004 \003(\0132\021.lionweb.Property\022*\n" +
      "\014containments\030\005 \003(\0132\024.lionweb.Containmen" +
      "t\022&\n\nreferences\030\006 \003(\0132\022.lionweb.Referenc" +
      "e\022\023\n\013annotations\030\007 \003(\r\".\n\010Property\022\023\n\013me" +
      "taPointer\030\001 \001(\r\022\r\n\005value\030\002 \001(\r\"4\n\013Contai" +
      "nment\022\023\n\013metaPointer\030\001 \001(\r\022\020\n\010children\030\002" +
      " \003(\r\"K\n\tReference\022\023\n\013metaPointer\030\001 \001(\r\022)" +
      "\n\007targets\030\002 \003(\0132\030.lionweb.ReferenceTarge" +
      "t\"9\n\017ReferenceTarget\022\021\n\treference\030\001 \001(\r\022" +
      "\023\n\013resolveInfo\030\002 \001(\rB=\n/io.lionweb.lionc" +
      "ore.java.serialization.protobufB\010Protobu" +
      "fP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lionweb_SerializationChunk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lionweb_SerializationChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_SerializationChunk_descriptor,
        new java.lang.String[] { "SerializationFormatVersion", "IdStrings", "MetaPointers", "Strings", "Languages", "Nodes", });
    internal_static_lionweb_SerializationChunk_IdStringsEntry_descriptor =
      internal_static_lionweb_SerializationChunk_descriptor.getNestedTypes().get(0);
    internal_static_lionweb_SerializationChunk_IdStringsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_SerializationChunk_IdStringsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lionweb_SerializationChunk_MetaPointersEntry_descriptor =
      internal_static_lionweb_SerializationChunk_descriptor.getNestedTypes().get(1);
    internal_static_lionweb_SerializationChunk_MetaPointersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_SerializationChunk_MetaPointersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lionweb_SerializationChunk_StringsEntry_descriptor =
      internal_static_lionweb_SerializationChunk_descriptor.getNestedTypes().get(2);
    internal_static_lionweb_SerializationChunk_StringsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_SerializationChunk_StringsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lionweb_CompactedId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lionweb_CompactedId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_CompactedId_descriptor,
        new java.lang.String[] { "Length", "Value", });
    internal_static_lionweb_MetaPointer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lionweb_MetaPointer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_MetaPointer_descriptor,
        new java.lang.String[] { "Language", "Version", "Key", });
    internal_static_lionweb_UsedLanguage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lionweb_UsedLanguage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_UsedLanguage_descriptor,
        new java.lang.String[] { "Language", "Version", });
    internal_static_lionweb_Node_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lionweb_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_Node_descriptor,
        new java.lang.String[] { "Id", "Parent", "Classifier", "Properties", "Containments", "References", "Annotations", });
    internal_static_lionweb_Property_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lionweb_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_Property_descriptor,
        new java.lang.String[] { "MetaPointer", "Value", });
    internal_static_lionweb_Containment_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lionweb_Containment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_Containment_descriptor,
        new java.lang.String[] { "MetaPointer", "Children", });
    internal_static_lionweb_Reference_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_lionweb_Reference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_Reference_descriptor,
        new java.lang.String[] { "MetaPointer", "Targets", });
    internal_static_lionweb_ReferenceTarget_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_lionweb_ReferenceTarget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lionweb_ReferenceTarget_descriptor,
        new java.lang.String[] { "Reference", "ResolveInfo", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
