// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

/**
 * Protobuf type {@code lionweb.ReferenceTarget}
 */
public final class ReferenceTarget extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:lionweb.ReferenceTarget)
    ReferenceTargetOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      ReferenceTarget.class.getName());
  }
  // Use ReferenceTarget.newBuilder() to construct.
  private ReferenceTarget(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ReferenceTarget() {
    resolveInfo_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_ReferenceTarget_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_ReferenceTarget_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.class, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder.class);
  }

  public static final int REFERENCE_FIELD_NUMBER = 1;
  private int reference_ = 0;
  /**
   * <code>uint32 reference = 1;</code>
   * @return The reference.
   */
  @java.lang.Override
  public int getReference() {
    return reference_;
  }

  public static final int RESOLVEINFO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resolveInfo_ = "";
  /**
   * <code>string resolveInfo = 2;</code>
   * @return The resolveInfo.
   */
  @java.lang.Override
  public java.lang.String getResolveInfo() {
    java.lang.Object ref = resolveInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resolveInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string resolveInfo = 2;</code>
   * @return The bytes for resolveInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResolveInfoBytes() {
    java.lang.Object ref = resolveInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resolveInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reference_ != 0) {
      output.writeUInt32(1, reference_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resolveInfo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, resolveInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reference_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, reference_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resolveInfo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, resolveInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget)) {
      return super.equals(obj);
    }
    io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget other = (io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget) obj;

    if (getReference()
        != other.getReference()) return false;
    if (!getResolveInfo()
        .equals(other.getResolveInfo())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + getReference();
    hash = (37 * hash) + RESOLVEINFO_FIELD_NUMBER;
    hash = (53 * hash) + getResolveInfo().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lionweb.ReferenceTarget}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lionweb.ReferenceTarget)
      io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_ReferenceTarget_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_ReferenceTarget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.class, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder.class);
    }

    // Construct using io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reference_ = 0;
      resolveInfo_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_ReferenceTarget_descriptor;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget getDefaultInstanceForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.getDefaultInstance();
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget build() {
      io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget buildPartial() {
      io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget result = new io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reference_ = reference_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.resolveInfo_ = resolveInfo_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget) {
        return mergeFrom((io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget other) {
      if (other == io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.getDefaultInstance()) return this;
      if (other.getReference() != 0) {
        setReference(other.getReference());
      }
      if (!other.getResolveInfo().isEmpty()) {
        resolveInfo_ = other.resolveInfo_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              reference_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              resolveInfo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int reference_ ;
    /**
     * <code>uint32 reference = 1;</code>
     * @return The reference.
     */
    @java.lang.Override
    public int getReference() {
      return reference_;
    }
    /**
     * <code>uint32 reference = 1;</code>
     * @param value The reference to set.
     * @return This builder for chaining.
     */
    public Builder setReference(int value) {

      reference_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 reference = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReference() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reference_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object resolveInfo_ = "";
    /**
     * <code>string resolveInfo = 2;</code>
     * @return The resolveInfo.
     */
    public java.lang.String getResolveInfo() {
      java.lang.Object ref = resolveInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resolveInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resolveInfo = 2;</code>
     * @return The bytes for resolveInfo.
     */
    public com.google.protobuf.ByteString
        getResolveInfoBytes() {
      java.lang.Object ref = resolveInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resolveInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resolveInfo = 2;</code>
     * @param value The resolveInfo to set.
     * @return This builder for chaining.
     */
    public Builder setResolveInfo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resolveInfo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string resolveInfo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResolveInfo() {
      resolveInfo_ = getDefaultInstance().getResolveInfo();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string resolveInfo = 2;</code>
     * @param value The bytes for resolveInfo to set.
     * @return This builder for chaining.
     */
    public Builder setResolveInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resolveInfo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:lionweb.ReferenceTarget)
  }

  // @@protoc_insertion_point(class_scope:lionweb.ReferenceTarget)
  private static final io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget();
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReferenceTarget>
      PARSER = new com.google.protobuf.AbstractParser<ReferenceTarget>() {
    @java.lang.Override
    public ReferenceTarget parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReferenceTarget> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReferenceTarget> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

