// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

public interface ReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lionweb.Reference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 metaPointer = 1;</code>
   * @return The metaPointer.
   */
  int getMetaPointer();

  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  java.util.List<io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget> 
      getTargetsList();
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget getTargets(int index);
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  int getTargetsCount();
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder> 
      getTargetsOrBuilderList();
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder getTargetsOrBuilder(
      int index);
}
