// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

/**
 * Protobuf type {@code lionweb.Reference}
 */
public final class Reference extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:lionweb.Reference)
    ReferenceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Reference.class.getName());
  }
  // Use Reference.newBuilder() to construct.
  private Reference(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Reference() {
    targets_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Reference_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Reference_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.lionweb.lioncore.java.serialization.protobuf.Reference.class, io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder.class);
  }

  public static final int METAPOINTER_FIELD_NUMBER = 1;
  private int metaPointer_ = 0;
  /**
   * <code>uint32 metaPointer = 1;</code>
   * @return The metaPointer.
   */
  @java.lang.Override
  public int getMetaPointer() {
    return metaPointer_;
  }

  public static final int TARGETS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget> targets_;
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget> getTargetsList() {
    return targets_;
  }
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder> 
      getTargetsOrBuilderList() {
    return targets_;
  }
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  @java.lang.Override
  public int getTargetsCount() {
    return targets_.size();
  }
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget getTargets(int index) {
    return targets_.get(index);
  }
  /**
   * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder getTargetsOrBuilder(
      int index) {
    return targets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metaPointer_ != 0) {
      output.writeUInt32(1, metaPointer_);
    }
    for (int i = 0; i < targets_.size(); i++) {
      output.writeMessage(2, targets_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metaPointer_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, metaPointer_);
    }
    for (int i = 0; i < targets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, targets_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.lionweb.lioncore.java.serialization.protobuf.Reference)) {
      return super.equals(obj);
    }
    io.lionweb.lioncore.java.serialization.protobuf.Reference other = (io.lionweb.lioncore.java.serialization.protobuf.Reference) obj;

    if (getMetaPointer()
        != other.getMetaPointer()) return false;
    if (!getTargetsList()
        .equals(other.getTargetsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METAPOINTER_FIELD_NUMBER;
    hash = (53 * hash) + getMetaPointer();
    if (getTargetsCount() > 0) {
      hash = (37 * hash) + TARGETS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.Reference parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.lionweb.lioncore.java.serialization.protobuf.Reference prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lionweb.Reference}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lionweb.Reference)
      io.lionweb.lioncore.java.serialization.protobuf.ReferenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Reference_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Reference_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.lionweb.lioncore.java.serialization.protobuf.Reference.class, io.lionweb.lioncore.java.serialization.protobuf.Reference.Builder.class);
    }

    // Construct using io.lionweb.lioncore.java.serialization.protobuf.Reference.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metaPointer_ = 0;
      if (targetsBuilder_ == null) {
        targets_ = java.util.Collections.emptyList();
      } else {
        targets_ = null;
        targetsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_Reference_descriptor;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Reference getDefaultInstanceForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Reference.getDefaultInstance();
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Reference build() {
      io.lionweb.lioncore.java.serialization.protobuf.Reference result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.Reference buildPartial() {
      io.lionweb.lioncore.java.serialization.protobuf.Reference result = new io.lionweb.lioncore.java.serialization.protobuf.Reference(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.lionweb.lioncore.java.serialization.protobuf.Reference result) {
      if (targetsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          targets_ = java.util.Collections.unmodifiableList(targets_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.targets_ = targets_;
      } else {
        result.targets_ = targetsBuilder_.build();
      }
    }

    private void buildPartial0(io.lionweb.lioncore.java.serialization.protobuf.Reference result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metaPointer_ = metaPointer_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.lionweb.lioncore.java.serialization.protobuf.Reference) {
        return mergeFrom((io.lionweb.lioncore.java.serialization.protobuf.Reference)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.lionweb.lioncore.java.serialization.protobuf.Reference other) {
      if (other == io.lionweb.lioncore.java.serialization.protobuf.Reference.getDefaultInstance()) return this;
      if (other.getMetaPointer() != 0) {
        setMetaPointer(other.getMetaPointer());
      }
      if (targetsBuilder_ == null) {
        if (!other.targets_.isEmpty()) {
          if (targets_.isEmpty()) {
            targets_ = other.targets_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTargetsIsMutable();
            targets_.addAll(other.targets_);
          }
          onChanged();
        }
      } else {
        if (!other.targets_.isEmpty()) {
          if (targetsBuilder_.isEmpty()) {
            targetsBuilder_.dispose();
            targetsBuilder_ = null;
            targets_ = other.targets_;
            bitField0_ = (bitField0_ & ~0x00000002);
            targetsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTargetsFieldBuilder() : null;
          } else {
            targetsBuilder_.addAllMessages(other.targets_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              metaPointer_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget m =
                  input.readMessage(
                      io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.parser(),
                      extensionRegistry);
              if (targetsBuilder_ == null) {
                ensureTargetsIsMutable();
                targets_.add(m);
              } else {
                targetsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int metaPointer_ ;
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @return The metaPointer.
     */
    @java.lang.Override
    public int getMetaPointer() {
      return metaPointer_;
    }
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @param value The metaPointer to set.
     * @return This builder for chaining.
     */
    public Builder setMetaPointer(int value) {

      metaPointer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 metaPointer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetaPointer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metaPointer_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget> targets_ =
      java.util.Collections.emptyList();
    private void ensureTargetsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        targets_ = new java.util.ArrayList<io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget>(targets_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder> targetsBuilder_;

    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget> getTargetsList() {
      if (targetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(targets_);
      } else {
        return targetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public int getTargetsCount() {
      if (targetsBuilder_ == null) {
        return targets_.size();
      } else {
        return targetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget getTargets(int index) {
      if (targetsBuilder_ == null) {
        return targets_.get(index);
      } else {
        return targetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder setTargets(
        int index, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.set(index, value);
        onChanged();
      } else {
        targetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder setTargets(
        int index, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.set(index, builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder addTargets(io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.add(value);
        onChanged();
      } else {
        targetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder addTargets(
        int index, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.add(index, value);
        onChanged();
      } else {
        targetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder addTargets(
        io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.add(builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder addTargets(
        int index, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.add(index, builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder addAllTargets(
        java.lang.Iterable<? extends io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget> values) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, targets_);
        onChanged();
      } else {
        targetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder clearTargets() {
      if (targetsBuilder_ == null) {
        targets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        targetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public Builder removeTargets(int index) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.remove(index);
        onChanged();
      } else {
        targetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder getTargetsBuilder(
        int index) {
      return getTargetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder getTargetsOrBuilder(
        int index) {
      if (targetsBuilder_ == null) {
        return targets_.get(index);  } else {
        return targetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder> 
         getTargetsOrBuilderList() {
      if (targetsBuilder_ != null) {
        return targetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(targets_);
      }
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder addTargetsBuilder() {
      return getTargetsFieldBuilder().addBuilder(
          io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder addTargetsBuilder(
        int index) {
      return getTargetsFieldBuilder().addBuilder(
          index, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.ReferenceTarget targets = 2;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder> 
         getTargetsBuilderList() {
      return getTargetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder> 
        getTargetsFieldBuilder() {
      if (targetsBuilder_ == null) {
        targetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTarget.Builder, io.lionweb.lioncore.java.serialization.protobuf.ReferenceTargetOrBuilder>(
                targets_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        targets_ = null;
      }
      return targetsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:lionweb.Reference)
  }

  // @@protoc_insertion_point(class_scope:lionweb.Reference)
  private static final io.lionweb.lioncore.java.serialization.protobuf.Reference DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.lionweb.lioncore.java.serialization.protobuf.Reference();
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.Reference getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Reference>
      PARSER = new com.google.protobuf.AbstractParser<Reference>() {
    @java.lang.Override
    public Reference parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Reference> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reference> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Reference getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

