// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

public interface ReferenceTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lionweb.ReferenceTarget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 reference = 1;</code>
   * @return The reference.
   */
  int getReference();

  /**
   * <code>uint32 resolveInfo = 2;</code>
   * @return The resolveInfo.
   */
  int getResolveInfo();
}
