// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lionweb.proto

// Protobuf Java Version: 4.26.1
package io.lionweb.lioncore.java.serialization.protobuf;

/**
 * Protobuf type {@code lionweb.SerializationChunk}
 */
public final class SerializationChunk extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:lionweb.SerializationChunk)
    SerializationChunkOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      SerializationChunk.class.getName());
  }
  // Use SerializationChunk.newBuilder() to construct.
  private SerializationChunk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SerializationChunk() {
    serializationFormatVersion_ = "";
    languages_ = java.util.Collections.emptyList();
    nodes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_SerializationChunk_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 2:
        return internalGetIdStrings();
      case 3:
        return internalGetMetaPointers();
      case 4:
        return internalGetStrings();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_SerializationChunk_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk.class, io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk.Builder.class);
  }

  public static final int SERIALIZATIONFORMATVERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serializationFormatVersion_ = "";
  /**
   * <code>string serializationFormatVersion = 1;</code>
   * @return The serializationFormatVersion.
   */
  @java.lang.Override
  public java.lang.String getSerializationFormatVersion() {
    java.lang.Object ref = serializationFormatVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serializationFormatVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string serializationFormatVersion = 1;</code>
   * @return The bytes for serializationFormatVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSerializationFormatVersionBytes() {
    java.lang.Object ref = serializationFormatVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serializationFormatVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDSTRINGS_FIELD_NUMBER = 2;
  private static final class IdStringsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId>newDefaultInstance(
                io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_SerializationChunk_IdStringsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.lionweb.lioncore.java.serialization.protobuf.CompactedId.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> idStrings_;
  private com.google.protobuf.MapField<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId>
  internalGetIdStrings() {
    if (idStrings_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          IdStringsDefaultEntryHolder.defaultEntry);
    }
    return idStrings_;
  }
  public int getIdStringsCount() {
    return internalGetIdStrings().getMap().size();
  }
  /**
   * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
   */
  @java.lang.Override
  public boolean containsIdStrings(
      int key) {

    return internalGetIdStrings().getMap().containsKey(key);
  }
  /**
   * Use {@link #getIdStringsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> getIdStrings() {
    return getIdStringsMap();
  }
  /**
   * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> getIdStringsMap() {
    return internalGetIdStrings().getMap();
  }
  /**
   * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
   */
  @java.lang.Override
  public /* nullable */
io.lionweb.lioncore.java.serialization.protobuf.CompactedId getIdStringsOrDefault(
      int key,
      /* nullable */
io.lionweb.lioncore.java.serialization.protobuf.CompactedId defaultValue) {

    java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> map =
        internalGetIdStrings().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.CompactedId getIdStringsOrThrow(
      int key) {

    java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> map =
        internalGetIdStrings().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int METAPOINTERS_FIELD_NUMBER = 3;
  private static final class MetaPointersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer>newDefaultInstance(
                io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_SerializationChunk_MetaPointersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.lionweb.lioncore.java.serialization.protobuf.MetaPointer.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> metaPointers_;
  private com.google.protobuf.MapField<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer>
  internalGetMetaPointers() {
    if (metaPointers_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetaPointersDefaultEntryHolder.defaultEntry);
    }
    return metaPointers_;
  }
  public int getMetaPointersCount() {
    return internalGetMetaPointers().getMap().size();
  }
  /**
   * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
   */
  @java.lang.Override
  public boolean containsMetaPointers(
      int key) {

    return internalGetMetaPointers().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetaPointersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> getMetaPointers() {
    return getMetaPointersMap();
  }
  /**
   * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> getMetaPointersMap() {
    return internalGetMetaPointers().getMap();
  }
  /**
   * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
   */
  @java.lang.Override
  public /* nullable */
io.lionweb.lioncore.java.serialization.protobuf.MetaPointer getMetaPointersOrDefault(
      int key,
      /* nullable */
io.lionweb.lioncore.java.serialization.protobuf.MetaPointer defaultValue) {

    java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> map =
        internalGetMetaPointers().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.MetaPointer getMetaPointersOrThrow(
      int key) {

    java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> map =
        internalGetMetaPointers().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int STRINGS_FIELD_NUMBER = 4;
  private static final class StringsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.String>newDefaultInstance(
                io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_SerializationChunk_StringsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.String> strings_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
  internalGetStrings() {
    if (strings_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StringsDefaultEntryHolder.defaultEntry);
    }
    return strings_;
  }
  public int getStringsCount() {
    return internalGetStrings().getMap().size();
  }
  /**
   * <code>map&lt;uint32, string&gt; strings = 4;</code>
   */
  @java.lang.Override
  public boolean containsStrings(
      int key) {

    return internalGetStrings().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStringsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.String> getStrings() {
    return getStringsMap();
  }
  /**
   * <code>map&lt;uint32, string&gt; strings = 4;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Integer, java.lang.String> getStringsMap() {
    return internalGetStrings().getMap();
  }
  /**
   * <code>map&lt;uint32, string&gt; strings = 4;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getStringsOrDefault(
      int key,
      /* nullable */
java.lang.String defaultValue) {

    java.util.Map<java.lang.Integer, java.lang.String> map =
        internalGetStrings().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;uint32, string&gt; strings = 4;</code>
   */
  @java.lang.Override
  public java.lang.String getStringsOrThrow(
      int key) {

    java.util.Map<java.lang.Integer, java.lang.String> map =
        internalGetStrings().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int LANGUAGES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage> languages_;
  /**
   * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
   */
  @java.lang.Override
  public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage> getLanguagesList() {
    return languages_;
  }
  /**
   * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.UsedLanguageOrBuilder> 
      getLanguagesOrBuilderList() {
    return languages_;
  }
  /**
   * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
   */
  @java.lang.Override
  public int getLanguagesCount() {
    return languages_.size();
  }
  /**
   * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage getLanguages(int index) {
    return languages_.get(index);
  }
  /**
   * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.UsedLanguageOrBuilder getLanguagesOrBuilder(
      int index) {
    return languages_.get(index);
  }

  public static final int NODES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Node> nodes_;
  /**
   * <code>repeated .lionweb.Node nodes = 6;</code>
   */
  @java.lang.Override
  public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Node> getNodesList() {
    return nodes_;
  }
  /**
   * <code>repeated .lionweb.Node nodes = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.NodeOrBuilder> 
      getNodesOrBuilderList() {
    return nodes_;
  }
  /**
   * <code>repeated .lionweb.Node nodes = 6;</code>
   */
  @java.lang.Override
  public int getNodesCount() {
    return nodes_.size();
  }
  /**
   * <code>repeated .lionweb.Node nodes = 6;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.Node getNodes(int index) {
    return nodes_.get(index);
  }
  /**
   * <code>repeated .lionweb.Node nodes = 6;</code>
   */
  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.NodeOrBuilder getNodesOrBuilder(
      int index) {
    return nodes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serializationFormatVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, serializationFormatVersion_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeIntegerMapTo(
        output,
        internalGetIdStrings(),
        IdStringsDefaultEntryHolder.defaultEntry,
        2);
    com.google.protobuf.GeneratedMessage
      .serializeIntegerMapTo(
        output,
        internalGetMetaPointers(),
        MetaPointersDefaultEntryHolder.defaultEntry,
        3);
    com.google.protobuf.GeneratedMessage
      .serializeIntegerMapTo(
        output,
        internalGetStrings(),
        StringsDefaultEntryHolder.defaultEntry,
        4);
    for (int i = 0; i < languages_.size(); i++) {
      output.writeMessage(5, languages_.get(i));
    }
    for (int i = 0; i < nodes_.size(); i++) {
      output.writeMessage(6, nodes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serializationFormatVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, serializationFormatVersion_);
    }
    for (java.util.Map.Entry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> entry
         : internalGetIdStrings().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId>
      idStrings__ = IdStringsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, idStrings__);
    }
    for (java.util.Map.Entry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> entry
         : internalGetMetaPointers().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer>
      metaPointers__ = MetaPointersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, metaPointers__);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
         : internalGetStrings().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
      strings__ = StringsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, strings__);
    }
    for (int i = 0; i < languages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, languages_.get(i));
    }
    for (int i = 0; i < nodes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, nodes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk)) {
      return super.equals(obj);
    }
    io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk other = (io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk) obj;

    if (!getSerializationFormatVersion()
        .equals(other.getSerializationFormatVersion())) return false;
    if (!internalGetIdStrings().equals(
        other.internalGetIdStrings())) return false;
    if (!internalGetMetaPointers().equals(
        other.internalGetMetaPointers())) return false;
    if (!internalGetStrings().equals(
        other.internalGetStrings())) return false;
    if (!getLanguagesList()
        .equals(other.getLanguagesList())) return false;
    if (!getNodesList()
        .equals(other.getNodesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERIALIZATIONFORMATVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getSerializationFormatVersion().hashCode();
    if (!internalGetIdStrings().getMap().isEmpty()) {
      hash = (37 * hash) + IDSTRINGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetIdStrings().hashCode();
    }
    if (!internalGetMetaPointers().getMap().isEmpty()) {
      hash = (37 * hash) + METAPOINTERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetaPointers().hashCode();
    }
    if (!internalGetStrings().getMap().isEmpty()) {
      hash = (37 * hash) + STRINGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStrings().hashCode();
    }
    if (getLanguagesCount() > 0) {
      hash = (37 * hash) + LANGUAGES_FIELD_NUMBER;
      hash = (53 * hash) + getLanguagesList().hashCode();
    }
    if (getNodesCount() > 0) {
      hash = (37 * hash) + NODES_FIELD_NUMBER;
      hash = (53 * hash) + getNodesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lionweb.SerializationChunk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lionweb.SerializationChunk)
      io.lionweb.lioncore.java.serialization.protobuf.SerializationChunkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_SerializationChunk_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetIdStrings();
        case 3:
          return internalGetMetaPointers();
        case 4:
          return internalGetStrings();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableIdStrings();
        case 3:
          return internalGetMutableMetaPointers();
        case 4:
          return internalGetMutableStrings();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_SerializationChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk.class, io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk.Builder.class);
    }

    // Construct using io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      serializationFormatVersion_ = "";
      internalGetMutableIdStrings().clear();
      internalGetMutableMetaPointers().clear();
      internalGetMutableStrings().clear();
      if (languagesBuilder_ == null) {
        languages_ = java.util.Collections.emptyList();
      } else {
        languages_ = null;
        languagesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
      } else {
        nodes_ = null;
        nodesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.Protobuf.internal_static_lionweb_SerializationChunk_descriptor;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk getDefaultInstanceForType() {
      return io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk.getDefaultInstance();
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk build() {
      io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk buildPartial() {
      io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk result = new io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk result) {
      if (languagesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          languages_ = java.util.Collections.unmodifiableList(languages_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.languages_ = languages_;
      } else {
        result.languages_ = languagesBuilder_.build();
      }
      if (nodesBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.nodes_ = nodes_;
      } else {
        result.nodes_ = nodesBuilder_.build();
      }
    }

    private void buildPartial0(io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.serializationFormatVersion_ = serializationFormatVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.idStrings_ = internalGetIdStrings().build(IdStringsDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.metaPointers_ = internalGetMetaPointers().build(MetaPointersDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.strings_ = internalGetStrings();
        result.strings_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk) {
        return mergeFrom((io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk other) {
      if (other == io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk.getDefaultInstance()) return this;
      if (!other.getSerializationFormatVersion().isEmpty()) {
        serializationFormatVersion_ = other.serializationFormatVersion_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutableIdStrings().mergeFrom(
          other.internalGetIdStrings());
      bitField0_ |= 0x00000002;
      internalGetMutableMetaPointers().mergeFrom(
          other.internalGetMetaPointers());
      bitField0_ |= 0x00000004;
      internalGetMutableStrings().mergeFrom(
          other.internalGetStrings());
      bitField0_ |= 0x00000008;
      if (languagesBuilder_ == null) {
        if (!other.languages_.isEmpty()) {
          if (languages_.isEmpty()) {
            languages_ = other.languages_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureLanguagesIsMutable();
            languages_.addAll(other.languages_);
          }
          onChanged();
        }
      } else {
        if (!other.languages_.isEmpty()) {
          if (languagesBuilder_.isEmpty()) {
            languagesBuilder_.dispose();
            languagesBuilder_ = null;
            languages_ = other.languages_;
            bitField0_ = (bitField0_ & ~0x00000010);
            languagesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getLanguagesFieldBuilder() : null;
          } else {
            languagesBuilder_.addAllMessages(other.languages_);
          }
        }
      }
      if (nodesBuilder_ == null) {
        if (!other.nodes_.isEmpty()) {
          if (nodes_.isEmpty()) {
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureNodesIsMutable();
            nodes_.addAll(other.nodes_);
          }
          onChanged();
        }
      } else {
        if (!other.nodes_.isEmpty()) {
          if (nodesBuilder_.isEmpty()) {
            nodesBuilder_.dispose();
            nodesBuilder_ = null;
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000020);
            nodesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNodesFieldBuilder() : null;
          } else {
            nodesBuilder_.addAllMessages(other.nodes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              serializationFormatVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId>
              idStrings__ = input.readMessage(
                  IdStringsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableIdStrings().ensureBuilderMap().put(
                  idStrings__.getKey(), idStrings__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer>
              metaPointers__ = input.readMessage(
                  MetaPointersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetaPointers().ensureBuilderMap().put(
                  metaPointers__.getKey(), metaPointers__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              strings__ = input.readMessage(
                  StringsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableStrings().getMutableMap().put(
                  strings__.getKey(), strings__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage m =
                  input.readMessage(
                      io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.parser(),
                      extensionRegistry);
              if (languagesBuilder_ == null) {
                ensureLanguagesIsMutable();
                languages_.add(m);
              } else {
                languagesBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              io.lionweb.lioncore.java.serialization.protobuf.Node m =
                  input.readMessage(
                      io.lionweb.lioncore.java.serialization.protobuf.Node.parser(),
                      extensionRegistry);
              if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.add(m);
              } else {
                nodesBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object serializationFormatVersion_ = "";
    /**
     * <code>string serializationFormatVersion = 1;</code>
     * @return The serializationFormatVersion.
     */
    public java.lang.String getSerializationFormatVersion() {
      java.lang.Object ref = serializationFormatVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serializationFormatVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serializationFormatVersion = 1;</code>
     * @return The bytes for serializationFormatVersion.
     */
    public com.google.protobuf.ByteString
        getSerializationFormatVersionBytes() {
      java.lang.Object ref = serializationFormatVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serializationFormatVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serializationFormatVersion = 1;</code>
     * @param value The serializationFormatVersion to set.
     * @return This builder for chaining.
     */
    public Builder setSerializationFormatVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serializationFormatVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string serializationFormatVersion = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerializationFormatVersion() {
      serializationFormatVersion_ = getDefaultInstance().getSerializationFormatVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string serializationFormatVersion = 1;</code>
     * @param value The bytes for serializationFormatVersion to set.
     * @return This builder for chaining.
     */
    public Builder setSerializationFormatVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serializationFormatVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private static final class IdStringsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> {
      @java.lang.Override
      public io.lionweb.lioncore.java.serialization.protobuf.CompactedId build(io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder val) {
        if (val instanceof io.lionweb.lioncore.java.serialization.protobuf.CompactedId) { return (io.lionweb.lioncore.java.serialization.protobuf.CompactedId) val; }
        return ((io.lionweb.lioncore.java.serialization.protobuf.CompactedId.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> defaultEntry() {
        return IdStringsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final IdStringsConverter idStringsConverter = new IdStringsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder, io.lionweb.lioncore.java.serialization.protobuf.CompactedId, io.lionweb.lioncore.java.serialization.protobuf.CompactedId.Builder> idStrings_;
    private com.google.protobuf.MapFieldBuilder<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder, io.lionweb.lioncore.java.serialization.protobuf.CompactedId, io.lionweb.lioncore.java.serialization.protobuf.CompactedId.Builder>
        internalGetIdStrings() {
      if (idStrings_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(idStringsConverter);
      }
      return idStrings_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder, io.lionweb.lioncore.java.serialization.protobuf.CompactedId, io.lionweb.lioncore.java.serialization.protobuf.CompactedId.Builder>
        internalGetMutableIdStrings() {
      if (idStrings_ == null) {
        idStrings_ = new com.google.protobuf.MapFieldBuilder<>(idStringsConverter);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return idStrings_;
    }
    public int getIdStringsCount() {
      return internalGetIdStrings().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
     */
    @java.lang.Override
    public boolean containsIdStrings(
        int key) {

      return internalGetIdStrings().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getIdStringsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> getIdStrings() {
      return getIdStringsMap();
    }
    /**
     * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> getIdStringsMap() {
      return internalGetIdStrings().getImmutableMap();
    }
    /**
     * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
io.lionweb.lioncore.java.serialization.protobuf.CompactedId getIdStringsOrDefault(
        int key,
        /* nullable */
io.lionweb.lioncore.java.serialization.protobuf.CompactedId defaultValue) {

      java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder> map = internalGetMutableIdStrings().ensureBuilderMap();
      return map.containsKey(key) ? idStringsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
     */
    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.CompactedId getIdStringsOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder> map = internalGetMutableIdStrings().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return idStringsConverter.build(map.get(key));
    }
    public Builder clearIdStrings() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableIdStrings().clear();
      return this;
    }
    /**
     * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
     */
    public Builder removeIdStrings(
        int key) {

      internalGetMutableIdStrings().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId>
        getMutableIdStrings() {
      bitField0_ |= 0x00000002;
      return internalGetMutableIdStrings().ensureMessageMap();
    }
    /**
     * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
     */
    public Builder putIdStrings(
        int key,
        io.lionweb.lioncore.java.serialization.protobuf.CompactedId value) {

      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableIdStrings().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
     */
    public Builder putAllIdStrings(
        java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> values) {
      for (java.util.Map.Entry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedId> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableIdStrings().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>map&lt;uint32, .lionweb.CompactedId&gt; idStrings = 2;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.CompactedId.Builder putIdStringsBuilderIfAbsent(
        int key) {
      java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder> builderMap = internalGetMutableIdStrings().ensureBuilderMap();
      io.lionweb.lioncore.java.serialization.protobuf.CompactedIdOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = io.lionweb.lioncore.java.serialization.protobuf.CompactedId.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof io.lionweb.lioncore.java.serialization.protobuf.CompactedId) {
        entry = ((io.lionweb.lioncore.java.serialization.protobuf.CompactedId) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (io.lionweb.lioncore.java.serialization.protobuf.CompactedId.Builder) entry;
    }

    private static final class MetaPointersConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> {
      @java.lang.Override
      public io.lionweb.lioncore.java.serialization.protobuf.MetaPointer build(io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder val) {
        if (val instanceof io.lionweb.lioncore.java.serialization.protobuf.MetaPointer) { return (io.lionweb.lioncore.java.serialization.protobuf.MetaPointer) val; }
        return ((io.lionweb.lioncore.java.serialization.protobuf.MetaPointer.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> defaultEntry() {
        return MetaPointersDefaultEntryHolder.defaultEntry;
      }
    };
    private static final MetaPointersConverter metaPointersConverter = new MetaPointersConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer.Builder> metaPointers_;
    private com.google.protobuf.MapFieldBuilder<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer.Builder>
        internalGetMetaPointers() {
      if (metaPointers_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(metaPointersConverter);
      }
      return metaPointers_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer.Builder>
        internalGetMutableMetaPointers() {
      if (metaPointers_ == null) {
        metaPointers_ = new com.google.protobuf.MapFieldBuilder<>(metaPointersConverter);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return metaPointers_;
    }
    public int getMetaPointersCount() {
      return internalGetMetaPointers().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
     */
    @java.lang.Override
    public boolean containsMetaPointers(
        int key) {

      return internalGetMetaPointers().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaPointersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> getMetaPointers() {
      return getMetaPointersMap();
    }
    /**
     * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> getMetaPointersMap() {
      return internalGetMetaPointers().getImmutableMap();
    }
    /**
     * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
io.lionweb.lioncore.java.serialization.protobuf.MetaPointer getMetaPointersOrDefault(
        int key,
        /* nullable */
io.lionweb.lioncore.java.serialization.protobuf.MetaPointer defaultValue) {

      java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder> map = internalGetMutableMetaPointers().ensureBuilderMap();
      return map.containsKey(key) ? metaPointersConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
     */
    @java.lang.Override
    public io.lionweb.lioncore.java.serialization.protobuf.MetaPointer getMetaPointersOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder> map = internalGetMutableMetaPointers().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return metaPointersConverter.build(map.get(key));
    }
    public Builder clearMetaPointers() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableMetaPointers().clear();
      return this;
    }
    /**
     * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
     */
    public Builder removeMetaPointers(
        int key) {

      internalGetMutableMetaPointers().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer>
        getMutableMetaPointers() {
      bitField0_ |= 0x00000004;
      return internalGetMutableMetaPointers().ensureMessageMap();
    }
    /**
     * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
     */
    public Builder putMetaPointers(
        int key,
        io.lionweb.lioncore.java.serialization.protobuf.MetaPointer value) {

      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetaPointers().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
     */
    public Builder putAllMetaPointers(
        java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> values) {
      for (java.util.Map.Entry<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointer> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableMetaPointers().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;uint32, .lionweb.MetaPointer&gt; metaPointers = 3;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.MetaPointer.Builder putMetaPointersBuilderIfAbsent(
        int key) {
      java.util.Map<java.lang.Integer, io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder> builderMap = internalGetMutableMetaPointers().ensureBuilderMap();
      io.lionweb.lioncore.java.serialization.protobuf.MetaPointerOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = io.lionweb.lioncore.java.serialization.protobuf.MetaPointer.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof io.lionweb.lioncore.java.serialization.protobuf.MetaPointer) {
        entry = ((io.lionweb.lioncore.java.serialization.protobuf.MetaPointer) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (io.lionweb.lioncore.java.serialization.protobuf.MetaPointer.Builder) entry;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> strings_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
        internalGetStrings() {
      if (strings_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StringsDefaultEntryHolder.defaultEntry);
      }
      return strings_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
        internalGetMutableStrings() {
      if (strings_ == null) {
        strings_ = com.google.protobuf.MapField.newMapField(
            StringsDefaultEntryHolder.defaultEntry);
      }
      if (!strings_.isMutable()) {
        strings_ = strings_.copy();
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return strings_;
    }
    public int getStringsCount() {
      return internalGetStrings().getMap().size();
    }
    /**
     * <code>map&lt;uint32, string&gt; strings = 4;</code>
     */
    @java.lang.Override
    public boolean containsStrings(
        int key) {

      return internalGetStrings().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStringsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getStrings() {
      return getStringsMap();
    }
    /**
     * <code>map&lt;uint32, string&gt; strings = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, java.lang.String> getStringsMap() {
      return internalGetStrings().getMap();
    }
    /**
     * <code>map&lt;uint32, string&gt; strings = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getStringsOrDefault(
        int key,
        /* nullable */
java.lang.String defaultValue) {

      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetStrings().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, string&gt; strings = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getStringsOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetStrings().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearStrings() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableStrings().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;uint32, string&gt; strings = 4;</code>
     */
    public Builder removeStrings(
        int key) {

      internalGetMutableStrings().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String>
        getMutableStrings() {
      bitField0_ |= 0x00000008;
      return internalGetMutableStrings().getMutableMap();
    }
    /**
     * <code>map&lt;uint32, string&gt; strings = 4;</code>
     */
    public Builder putStrings(
        int key,
        java.lang.String value) {

      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableStrings().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>map&lt;uint32, string&gt; strings = 4;</code>
     */
    public Builder putAllStrings(
        java.util.Map<java.lang.Integer, java.lang.String> values) {
      internalGetMutableStrings().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }

    private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage> languages_ =
      java.util.Collections.emptyList();
    private void ensureLanguagesIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        languages_ = new java.util.ArrayList<io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage>(languages_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguageOrBuilder> languagesBuilder_;

    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage> getLanguagesList() {
      if (languagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(languages_);
      } else {
        return languagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public int getLanguagesCount() {
      if (languagesBuilder_ == null) {
        return languages_.size();
      } else {
        return languagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage getLanguages(int index) {
      if (languagesBuilder_ == null) {
        return languages_.get(index);
      } else {
        return languagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder setLanguages(
        int index, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage value) {
      if (languagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLanguagesIsMutable();
        languages_.set(index, value);
        onChanged();
      } else {
        languagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder setLanguages(
        int index, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder builderForValue) {
      if (languagesBuilder_ == null) {
        ensureLanguagesIsMutable();
        languages_.set(index, builderForValue.build());
        onChanged();
      } else {
        languagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder addLanguages(io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage value) {
      if (languagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLanguagesIsMutable();
        languages_.add(value);
        onChanged();
      } else {
        languagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder addLanguages(
        int index, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage value) {
      if (languagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLanguagesIsMutable();
        languages_.add(index, value);
        onChanged();
      } else {
        languagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder addLanguages(
        io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder builderForValue) {
      if (languagesBuilder_ == null) {
        ensureLanguagesIsMutable();
        languages_.add(builderForValue.build());
        onChanged();
      } else {
        languagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder addLanguages(
        int index, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder builderForValue) {
      if (languagesBuilder_ == null) {
        ensureLanguagesIsMutable();
        languages_.add(index, builderForValue.build());
        onChanged();
      } else {
        languagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder addAllLanguages(
        java.lang.Iterable<? extends io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage> values) {
      if (languagesBuilder_ == null) {
        ensureLanguagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, languages_);
        onChanged();
      } else {
        languagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder clearLanguages() {
      if (languagesBuilder_ == null) {
        languages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        languagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public Builder removeLanguages(int index) {
      if (languagesBuilder_ == null) {
        ensureLanguagesIsMutable();
        languages_.remove(index);
        onChanged();
      } else {
        languagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder getLanguagesBuilder(
        int index) {
      return getLanguagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.UsedLanguageOrBuilder getLanguagesOrBuilder(
        int index) {
      if (languagesBuilder_ == null) {
        return languages_.get(index);  } else {
        return languagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.UsedLanguageOrBuilder> 
         getLanguagesOrBuilderList() {
      if (languagesBuilder_ != null) {
        return languagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(languages_);
      }
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder addLanguagesBuilder() {
      return getLanguagesFieldBuilder().addBuilder(
          io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder addLanguagesBuilder(
        int index) {
      return getLanguagesFieldBuilder().addBuilder(
          index, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.UsedLanguage languages = 5;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder> 
         getLanguagesBuilderList() {
      return getLanguagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguageOrBuilder> 
        getLanguagesFieldBuilder() {
      if (languagesBuilder_ == null) {
        languagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguage.Builder, io.lionweb.lioncore.java.serialization.protobuf.UsedLanguageOrBuilder>(
                languages_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        languages_ = null;
      }
      return languagesBuilder_;
    }

    private java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Node> nodes_ =
      java.util.Collections.emptyList();
    private void ensureNodesIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        nodes_ = new java.util.ArrayList<io.lionweb.lioncore.java.serialization.protobuf.Node>(nodes_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.Node, io.lionweb.lioncore.java.serialization.protobuf.Node.Builder, io.lionweb.lioncore.java.serialization.protobuf.NodeOrBuilder> nodesBuilder_;

    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Node> getNodesList() {
      if (nodesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nodes_);
      } else {
        return nodesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public int getNodesCount() {
      if (nodesBuilder_ == null) {
        return nodes_.size();
      } else {
        return nodesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Node getNodes(int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);
      } else {
        return nodesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder setNodes(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Node value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.set(index, value);
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder setNodes(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Node.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder addNodes(io.lionweb.lioncore.java.serialization.protobuf.Node value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder addNodes(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Node value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(index, value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder addNodes(
        io.lionweb.lioncore.java.serialization.protobuf.Node.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder addNodes(
        int index, io.lionweb.lioncore.java.serialization.protobuf.Node.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder addAllNodes(
        java.lang.Iterable<? extends io.lionweb.lioncore.java.serialization.protobuf.Node> values) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodes_);
        onChanged();
      } else {
        nodesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder clearNodes() {
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        nodesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public Builder removeNodes(int index) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.remove(index);
        onChanged();
      } else {
        nodesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Node.Builder getNodesBuilder(
        int index) {
      return getNodesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.NodeOrBuilder getNodesOrBuilder(
        int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);  } else {
        return nodesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public java.util.List<? extends io.lionweb.lioncore.java.serialization.protobuf.NodeOrBuilder> 
         getNodesOrBuilderList() {
      if (nodesBuilder_ != null) {
        return nodesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nodes_);
      }
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Node.Builder addNodesBuilder() {
      return getNodesFieldBuilder().addBuilder(
          io.lionweb.lioncore.java.serialization.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public io.lionweb.lioncore.java.serialization.protobuf.Node.Builder addNodesBuilder(
        int index) {
      return getNodesFieldBuilder().addBuilder(
          index, io.lionweb.lioncore.java.serialization.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .lionweb.Node nodes = 6;</code>
     */
    public java.util.List<io.lionweb.lioncore.java.serialization.protobuf.Node.Builder> 
         getNodesBuilderList() {
      return getNodesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.lionweb.lioncore.java.serialization.protobuf.Node, io.lionweb.lioncore.java.serialization.protobuf.Node.Builder, io.lionweb.lioncore.java.serialization.protobuf.NodeOrBuilder> 
        getNodesFieldBuilder() {
      if (nodesBuilder_ == null) {
        nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.lionweb.lioncore.java.serialization.protobuf.Node, io.lionweb.lioncore.java.serialization.protobuf.Node.Builder, io.lionweb.lioncore.java.serialization.protobuf.NodeOrBuilder>(
                nodes_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        nodes_ = null;
      }
      return nodesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:lionweb.SerializationChunk)
  }

  // @@protoc_insertion_point(class_scope:lionweb.SerializationChunk)
  private static final io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk();
  }

  public static io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SerializationChunk>
      PARSER = new com.google.protobuf.AbstractParser<SerializationChunk>() {
    @java.lang.Override
    public SerializationChunk parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SerializationChunk> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SerializationChunk> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.lionweb.lioncore.java.serialization.protobuf.SerializationChunk getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

