package io.lionweb.gradleplugin;

import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.MapProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.SetProperty;

/**
 * Gradle extension for configuring the LionWeb Gradle plugin.
 *
 * <p>Configure this extension in your build script using the {@code lionweb} block after applying
 * the {@code io.lionweb} plugin. The plugin wires these settings into the {@code
 * generateLWLanguages} and {@code generateLWNodeClasses} tasks.
 *
 * <p>Default conventions provided by the plugin:
 *
 * <ul>
 *   <li>{@link #getLanguagesDirectory()} defaults to {@code src/main/lionweb}
 *   <li>{@link #getGenerationDirectory()} defaults to {@code build/generated-lionweb}
 * </ul>
 *
 * <p>Example (Kotlin DSL):
 *
 * <pre>{@code
 * lionweb {
 *
 *   // Where to look for language definitions, defaults to src/main/lionweb
 *   languagesDirectory = layout.projectDirectory.dir("my-dir-full-of-languages")
 *
 *   // Set the package names with a global default and specific settings
 *   defaultPackageName = "com.example.languages"
 *   languagesSpecificPackages = mapOf("com_example_mylanguage_id" to "com.example.mylanguage")
 *
 *   // Defaults to build/generated-lionweb
 *   generationDirectory.set(layout.buildDirectory.dir("my-generation-dir"))
 *
 *   // If we want to force the Language Class to have a specific name, we can
 *   languagesClassNames = mapOf"com.example.mylanguage" to "MyLanguage")
 *
 *   // If we want to generate code only for some of the languages (as the others are just dependencies,
 *   // for example), we can use this setting
 *   languagesToGenerate = setOf("MyLanguage")
 *
 *   // Classes for primitive types must be written manually and specified here
 *   primitiveTypes = mapOf("com.example.types.Instant" to "java.time.Instant")
 *
 *   // Our language may refer to concepts for which a class has been already written. If so,
 *   // this setting let the generator know about it.
 *   mappings = mapOf("com.example.other.MyConcept" to "com.example.other.MyConceptImpl")
 * }
 * }</pre>
 */
public abstract class LionWebPluginExtension {

  /**
   * Base package for generated Java sources.
   *
   * <p>This is used when a language does not have a specific package configured in {@link
   * #getLanguagesSpecificPackages()}. If you do not provide a default package, then every language
   * that is generated must have an entry in {@link #getLanguagesSpecificPackages()}.
   */
  public abstract Property<String> getDefaultPackageName();

  /**
   * Directory containing LionWeb language definitions to load from the project.
   *
   * <p>Files under this directory are scanned recursively. The plugin currently supports JSON
   * serialization files (extension {@code .json}). Protobuf files ({@code .pb}) are discovered but
   * not yet supported by the generator.
   *
   * <p>When creating the project's JAR, the plugin also packages these language files under {@code
   * META-INF/lionweb}.
   */
  public abstract DirectoryProperty getLanguagesDirectory();

  /**
   * Destination directory for generated Java sources.
   *
   * <p>Both {@code generateLWLanguages} and {@code generateLWNodeClasses} write output to this
   * directory.
   */
  public abstract DirectoryProperty getGenerationDirectory();

  /**
   * Maps LionWeb primitive type IDs to Java fully qualified class names.
   *
   * <p>Keys are LionWeb primitive type identifiers as found in the serialized language definitions
   * (for example, {@code com.example.types.Instant}). Values are Java type names such as {@code
   * java.time.Instant}. This mapping is used by {@code generateLWNodeClasses} when generating
   * fields for primitive-typed properties.
   */
  public abstract MapProperty<String, String> getPrimitiveTypes();

  /**
   * Maps LionWeb language IDs to the Java package in which code for that language should be
   * generated.
   *
   * <p>When a language ID is not present in this map, {@link #getDefaultPackageName()} is used
   * instead.
   */
  public abstract MapProperty<String, String> getLanguagesSpecificPackages();

  /**
   * Maps LionWeb language IDs to the class name of the generated {@code Language} Java class.
   *
   * <p>If a language ID is not present, the default naming strategy is used.
   */
  public abstract MapProperty<String, String> getLanguagesClassNames();

  /**
   * Restricts generation to a subset of languages.
   *
   * <p>Entries can be language names, IDs, or keys. If unset, the generators produce code for all
   * languages loaded from the project language files.
   */
  public abstract SetProperty<String> getLanguagesToGenerate();

  /**
   * Maps LionWeb classifier qualified names to Java fully qualified class names.
   *
   * <p>This is used when generated code references classifiers that are not generated by this
   * plugin (for example, concepts or interfaces from external languages). The key must match {@code
   * classifier.qualifiedName()} from the LionWeb language model.
   */
  public abstract MapProperty<String, String> getMappings();
}
