// automatically generated by the FlatBuffers compiler, do not modify

package io.lionweb.lioncore.java.serialization.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBContainment extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static FBContainment getRootAsFBContainment(ByteBuffer _bb) { return getRootAsFBContainment(_bb, new FBContainment()); }
  public static FBContainment getRootAsFBContainment(ByteBuffer _bb, FBContainment obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBContainment __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int metaPointerIndex() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int children(int j) { int o = __offset(6); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int childrenLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public IntVector childrenVector() { return childrenVector(new IntVector()); }
  public IntVector childrenVector(IntVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer childrenAsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer childrenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }

  public static int createFBContainment(FlatBufferBuilder builder,
      int metaPointerIndex,
      int childrenOffset) {
    builder.startTable(2);
    FBContainment.addChildren(builder, childrenOffset);
    FBContainment.addMetaPointerIndex(builder, metaPointerIndex);
    return FBContainment.endFBContainment(builder);
  }

  public static void startFBContainment(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addMetaPointerIndex(FlatBufferBuilder builder, int metaPointerIndex) { builder.addInt(0, metaPointerIndex, 0); }
  public static void addChildren(FlatBufferBuilder builder, int childrenOffset) { builder.addOffset(1, childrenOffset, 0); }
  public static int createChildrenVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startChildrenVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFBContainment(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBContainment get(int j) { return get(new FBContainment(), j); }
    public FBContainment get(FBContainment obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

