// automatically generated by the FlatBuffers compiler, do not modify

package io.lionweb.lioncore.java.serialization.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBLanguage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static FBLanguage getRootAsFBLanguage(ByteBuffer _bb) { return getRootAsFBLanguage(_bb, new FBLanguage()); }
  public static FBLanguage getRootAsFBLanguage(ByteBuffer _bb, FBLanguage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBLanguage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int key() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int version() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFBLanguage(FlatBufferBuilder builder,
      int key,
      int version) {
    builder.startTable(2);
    FBLanguage.addVersion(builder, version);
    FBLanguage.addKey(builder, key);
    return FBLanguage.endFBLanguage(builder);
  }

  public static void startFBLanguage(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addKey(FlatBufferBuilder builder, int key) { builder.addInt(0, key, 0); }
  public static void addVersion(FlatBufferBuilder builder, int version) { builder.addInt(1, version, 0); }
  public static int endFBLanguage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBLanguage get(int j) { return get(new FBLanguage(), j); }
    public FBLanguage get(FBLanguage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

