// automatically generated by the FlatBuffers compiler, do not modify

package io.lionweb.lioncore.java.serialization.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBReference extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static FBReference getRootAsFBReference(ByteBuffer _bb) { return getRootAsFBReference(_bb, new FBReference()); }
  public static FBReference getRootAsFBReference(ByteBuffer _bb, FBReference obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBReference __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int metaPointerIndex() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public FBReferenceValue values(int j) { return values(new FBReferenceValue(), j); }
  public FBReferenceValue values(FBReferenceValue obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int valuesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public FBReferenceValue.Vector valuesVector() { return valuesVector(new FBReferenceValue.Vector()); }
  public FBReferenceValue.Vector valuesVector(FBReferenceValue.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createFBReference(FlatBufferBuilder builder,
      int metaPointerIndex,
      int valuesOffset) {
    builder.startTable(2);
    FBReference.addValues(builder, valuesOffset);
    FBReference.addMetaPointerIndex(builder, metaPointerIndex);
    return FBReference.endFBReference(builder);
  }

  public static void startFBReference(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addMetaPointerIndex(FlatBufferBuilder builder, int metaPointerIndex) { builder.addInt(0, metaPointerIndex, 0); }
  public static void addValues(FlatBufferBuilder builder, int valuesOffset) { builder.addOffset(1, valuesOffset, 0); }
  public static int createValuesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFBReference(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBReference get(int j) { return get(new FBReference(), j); }
    public FBReference get(FBReference obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

