// automatically generated by the FlatBuffers compiler, do not modify

package io.lionweb.lioncore.java.serialization.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FBReferenceValue extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static FBReferenceValue getRootAsFBReferenceValue(ByteBuffer _bb) { return getRootAsFBReferenceValue(_bb, new FBReferenceValue()); }
  public static FBReferenceValue getRootAsFBReferenceValue(ByteBuffer _bb, FBReferenceValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FBReferenceValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int resolveInfo() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int referred() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFBReferenceValue(FlatBufferBuilder builder,
      int resolveInfo,
      int referred) {
    builder.startTable(2);
    FBReferenceValue.addReferred(builder, referred);
    FBReferenceValue.addResolveInfo(builder, resolveInfo);
    return FBReferenceValue.endFBReferenceValue(builder);
  }

  public static void startFBReferenceValue(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addResolveInfo(FlatBufferBuilder builder, int resolveInfo) { builder.addInt(0, resolveInfo, 0); }
  public static void addReferred(FlatBufferBuilder builder, int referred) { builder.addInt(1, referred, 0); }
  public static int endFBReferenceValue(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FBReferenceValue get(int j) { return get(new FBReferenceValue(), j); }
    public FBReferenceValue get(FBReferenceValue obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

