module.exports = {
    tutorialSidebar: [
        'index',
        'about-lionweb',
        {
          type: 'category',
          label: 'About this project',
          items: [{ type: 'autogenerated', dirName: 'About this project' }],
        },
        {
          type: 'category',
          label: 'Introduction',
          items: [{ type: 'autogenerated', dirName: 'Introduction' }],
        },
        {
          type: 'category',
          label: 'Architecture',
          items: [{ type: 'autogenerated', dirName: 'Architecture' }],
        },
        {
          type: 'category',
          label: 'Guides',
          items: [{ type: 'autogenerated', dirName: 'Guides' }],
        },
    ],
  };