name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    name: Java ${{ matrix.Java }} BuildAndTest

    steps:
    - uses: actions/checkout@v5
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Test
      run: ./gradlew check