name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21', '25' ]
    name: Java ${{ matrix.java }} Build and Test

    steps:
    - uses: actions/checkout@v6
    - name: Setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Check formatting
      run: ./gradlew spotlessCheck
    - name: Test
      run: ./gradlew check
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: test-results-java-${{ matrix.java }}
        path: '**/build/test-results/**/*.xml'
        retention-days: 7

  functional-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '25' ]
    name: Java ${{ matrix.java }} Functional Tests

    steps:
    - uses: actions/checkout@v6
    - name: Setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Functional Tests
      run: ./gradlew functionalTest --stacktrace
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: functional-test-results-java-${{ matrix.java }}
        path: '**/build/test-results/**/*.xml'
        retention-days: 7

  core-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '25' ]
    name: Java ${{ matrix.java }} Core Integration Tests

    steps:
    - uses: actions/checkout@v6
    - name: Setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Core Integration Tests
      run: ./gradlew :core:integrationTest --stacktrace --info
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: core-integration-test-results-java-${{ matrix.java }}
        path: '**/build/test-results/**/*.xml'
        retention-days: 7

  client-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '25' ]
    name: Java ${{ matrix.java }} Client Integration Tests

    steps:
      - uses: actions/checkout@v6
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Client Integration Tests
        run: ./gradlew :client:integrationTest --stacktrace --info
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: client-integration-test-results-java-${{ matrix.java }}
          path: '**/build/test-results/**/*.xml'
          retention-days: 7

  server-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '25' ]
    name: Java ${{ matrix.java }} Server Integration Tests

    steps:
      - uses: actions/checkout@v6
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Server Integration Tests
        run: ./gradlew :server:integrationTest --stacktrace --info
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: server-integration-test-results-java-${{ matrix.java }}
          path: '**/build/test-results/**/*.xml'
          retention-days: 7

  plugin-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '25' ]
    name: Java ${{ matrix.java }} Plugin Integration Tests

    steps:
    - uses: actions/checkout@v6
    - name: Setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Plugin Integration Tests
      run: ./gradlew :gradle-plugin:integrationTest
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: plugin-integration-test-results-java-${{ matrix.java }}
        path: 'gradle-plugin/build/test-results/integrationTest/**/*.xml'
        retention-days: 7

  javadoc:
    runs-on: ubuntu-latest
    name: Javadoc

    steps:
    - uses: actions/checkout@v6
    - name: Setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Javadoc generation
      run: ./gradlew myJavadoc
