name: Test docs deployment

on:
  pull_request:
    branches:
      - master

jobs:
  test-docs-deploy:
    name: Test deployment
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: website

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
